<?php
/**
 * ProCut - Seed 25 Real, Fully Editable Online Templates
 * Populates database with complete editable project definitions (project_json).
 */

require_once __DIR__ . '/../config/database.php';

$pdo = Database::getConnection();

echo "Starting seeding 25 fully editable online templates...\n";

// Array of 25 comprehensive templates
$templates = [
    [
        'id' => 'tmpl-birthday',
        'category' => 'Birthday',
        'badge' => 'Celebration',
        'title' => '🎉 Birthday Celebration Highlights',
        'description' => 'Fun confetti pops, celebration typography, warm party filters and upbeat pop background music.',
        'prompt' => 'Vibrant birthday celebration reel with confetti burst, smiling candle blowout, joyful group cheering, colorful party lighting.',
        'author' => 'PartyLab Studio',
        'aspect_ratio' => 'ratio9_16',
        'duration_ms' => 12000,
        'clips_count' => 3,
        'downloads_count' => 34200,
        'preview_gradient_start' => '0xFFFF5E3A',
        'preview_gradient_end' => '0xFFFF2A68',
        'preview_video_url' => '/media/templates/alps_sunrise.mp4',
        'preview_image_url' => '/media/templates/tmpl-golden-hour.jpg',
        'audio_title' => 'Birthday Party Pop Beats',
        'audio_url' => '/media/templates/tropical_beat.wav',
        'tags' => 'Birthday,Party,Celebration,Balloons,Cake,Family',
        'is_pro' => 0,
        'is_trending' => 1,
        'is_new' => 0,
        'is_popular' => 1,
        'display_order' => 1,
        'slots' => [
            ['duration' => 4000, 'filter' => 'warm', 'transition' => 'zoomIn', 'media' => 'assets/demo/alps_sunrise.mp4'],
            ['duration' => 4000, 'filter' => 'vintage', 'transition' => 'fade', 'media' => 'assets/demo/ramen_bar.mp4'],
            ['duration' => 4000, 'filter' => 'vivid', 'transition' => 'zoomIn', 'media' => 'assets/demo/tokyo_shinjuku.mp4'],
        ],
        'texts' => [
            ['text' => 'Happy Birthday! 🎂', 'font' => 'Inter', 'size' => 28, 'color' => 0xFFFFFFFF, 'bg' => 0xFFFF2A68, 'start' => 0, 'end' => 6000, 'anim' => 'scale', 'x' => 0.5, 'y' => 0.2],
            ['text' => 'Make A Wish ✨', 'font' => 'SpaceMono', 'size' => 20, 'color' => 0xFFFFF176, 'bg' => null, 'start' => 6000, 'end' => 12000, 'anim' => 'slideUp', 'x' => 0.5, 'y' => 0.8],
        ]
    ],
    [
        'id' => 'tmpl-wedding',
        'category' => 'Wedding',
        'badge' => 'Romantic',
        'title' => '💍 Eternal Vows Wedding Film',
        'description' => 'Romantic slow-motion dissolves, elegant golden bokeh lighting, and emotional cinematic orchestra.',
        'prompt' => 'Ultra high-end luxury cinematic wedding teaser film, golden hour bride veil fluttering in sea breeze, groom emotional reaction.',
        'author' => 'Elegance Films',
        'aspect_ratio' => 'ratio9_16',
        'duration_ms' => 15000,
        'clips_count' => 4,
        'downloads_count' => 52100,
        'preview_gradient_start' => '0xFFD4AF37',
        'preview_gradient_end' => '0xFFF3E5AB',
        'preview_video_url' => '/media/templates/alps_drone.mp4',
        'preview_image_url' => '/media/templates/tmpl-golden-hour.jpg',
        'audio_title' => 'Eternal Romance Strings',
        'audio_url' => '/media/templates/cinematic_audio.wav',
        'tags' => 'Wedding,Bride,Groom,Love,Ceremony,Romance',
        'is_pro' => 1,
        'is_trending' => 1,
        'is_new' => 0,
        'is_popular' => 1,
        'display_order' => 2,
        'slots' => [
            ['duration' => 3750, 'filter' => 'vintage', 'transition' => 'fade', 'media' => 'assets/demo/alps_drone.mp4'],
            ['duration' => 3750, 'filter' => 'warm', 'transition' => 'crossfade', 'media' => 'assets/demo/alps_sunrise.mp4'],
            ['duration' => 3750, 'filter' => 'softWarm', 'transition' => 'fade', 'media' => 'assets/demo/sunset_beach.jpg'],
            ['duration' => 3750, 'filter' => 'vintage', 'transition' => 'zoomIn', 'media' => 'assets/demo/ramen_bar.mp4'],
        ],
        'texts' => [
            ['text' => 'Forever & Always 💍', 'font' => 'Inter', 'size' => 26, 'color' => 0xFFFFFFFF, 'bg' => 0xFF2A2A2A, 'start' => 0, 'end' => 7500, 'anim' => 'fade', 'x' => 0.5, 'y' => 0.25],
            ['text' => 'The Wedding Story', 'font' => 'SpaceMono', 'size' => 18, 'color' => 0xFFD4AF37, 'bg' => null, 'start' => 7500, 'end' => 15000, 'anim' => 'typewriter', 'x' => 0.5, 'y' => 0.85],
        ]
    ],
    [
        'id' => 'tmpl-travel',
        'category' => 'Travel',
        'badge' => 'Adventure',
        'title' => '✈️ Wanderlust Adventure Recap',
        'description' => 'Dynamic whip transitions, GPS coordinate titles, vibrant saturation, and tropical travel vibes.',
        'prompt' => 'Fast-paced travel vlog reel, cliff diving into crystal blue water, mountain peaks drone flyover, authentic local street food markets.',
        'author' => 'Global Roamer',
        'aspect_ratio' => 'ratio9_16',
        'duration_ms' => 14000,
        'clips_count' => 4,
        'downloads_count' => 61000,
        'preview_gradient_start' => '0xFF00B4DB',
        'preview_gradient_end' => '0xFF0083B0',
        'preview_video_url' => '/media/templates/alps_drone.mp4',
        'preview_image_url' => '/media/templates/tmpl-summer-tropical.jpg',
        'audio_title' => 'Tropical Horizon Beats',
        'audio_url' => '/media/templates/tropical_beat.wav',
        'tags' => 'Travel,Adventure,Vacation,Wanderlust,Nature,Summer',
        'is_pro' => 0,
        'is_trending' => 1,
        'is_new' => 0,
        'is_popular' => 1,
        'display_order' => 3,
        'slots' => [
            ['duration' => 3500, 'filter' => 'vibrant', 'transition' => 'slideLeft', 'media' => 'assets/demo/alps_drone.mp4'],
            ['duration' => 3500, 'filter' => 'punchy', 'transition' => 'zoomIn', 'media' => 'assets/demo/alps_sunrise.mp4'],
            ['duration' => 3500, 'filter' => 'vibrant', 'transition' => 'slideRight', 'media' => 'assets/demo/sunset_beach.jpg'],
            ['duration' => 3500, 'filter' => 'cleanPop', 'transition' => 'fade', 'media' => 'assets/demo/tokyo_street.mp4'],
        ],
        'texts' => [
            ['text' => 'WANDERLUST ✈️', 'font' => 'Inter', 'size' => 30, 'color' => 0xFFFFFFFF, 'bg' => 0xFF0083B0, 'start' => 0, 'end' => 7000, 'anim' => 'slideUp', 'x' => 0.5, 'y' => 0.18],
            ['text' => 'Next Destination 📍', 'font' => 'SpaceMono', 'size' => 18, 'color' => 0xFFE0F7FA, 'bg' => null, 'start' => 7000, 'end' => 14000, 'anim' => 'typewriter', 'x' => 0.5, 'y' => 0.82],
        ]
    ],
    [
        'id' => 'tmpl-love-story',
        'category' => 'Love Story',
        'badge' => 'Sweet',
        'title' => '❤️ Our Love Story Moments',
        'description' => 'Soft pastel tones, heart stickers, dreamy blur transitions, and acoustic lo-fi vibes.',
        'prompt' => 'Romantic couple vlog, holding hands walking on sunset boardwalk, giggling coffee shop candid moments, golden warm glow.',
        'author' => 'Sweet Memories',
        'aspect_ratio' => 'ratio9_16',
        'duration_ms' => 12000,
        'clips_count' => 3,
        'downloads_count' => 41800,
        'preview_gradient_start' => '0xFFFF758C',
        'preview_gradient_end' => '0xFFFF7EB3',
        'preview_video_url' => '/media/templates/alps_sunrise.mp4',
        'preview_image_url' => '/media/templates/tmpl-golden-hour.jpg',
        'audio_title' => 'Lo-Fi Romance Dream',
        'audio_url' => '/media/templates/lofi_beat.wav',
        'tags' => 'Love,Couple,Romantic,Cute,Relationship,Heart',
        'is_pro' => 0,
        'is_trending' => 0,
        'is_new' => 1,
        'is_popular' => 1,
        'display_order' => 4,
        'slots' => [
            ['duration' => 4000, 'filter' => 'softWarm', 'transition' => 'fade', 'media' => 'assets/demo/sunset_beach.jpg'],
            ['duration' => 4000, 'filter' => 'vintage', 'transition' => 'zoomIn', 'media' => 'assets/demo/alps_sunrise.mp4'],
            ['duration' => 4000, 'filter' => 'warm', 'transition' => 'fade', 'media' => 'assets/demo/ramen_bar.mp4'],
        ],
        'texts' => [
            ['text' => 'You & Me ❤️', 'font' => 'Inter', 'size' => 26, 'color' => 0xFFFFFFFF, 'bg' => 0xFFFF758C, 'start' => 0, 'end' => 6000, 'anim' => 'scale', 'x' => 0.5, 'y' => 0.22],
            ['text' => 'Every Second With You', 'font' => 'SpaceMono', 'size' => 18, 'color' => 0xFFFFE4E6, 'bg' => null, 'start' => 6000, 'end' => 12000, 'anim' => 'fade', 'x' => 0.5, 'y' => 0.85],
        ]
    ],
    [
        'id' => 'tmpl-family',
        'category' => 'Family',
        'badge' => 'Warm',
        'title' => '🏡 Home & Family Memories',
        'description' => 'Warm home-video vibes, gentle fades, nostalgic warmth, and joyful acoustic rhythms.',
        'prompt' => 'Heartwarming family moments at home, kids laughing in garden, baking cookies together, grandparents warm smiles.',
        'author' => 'Kinfolk Media',
        'aspect_ratio' => 'ratio9_16',
        'duration_ms' => 12000,
        'clips_count' => 4,
        'downloads_count' => 29500,
        'preview_gradient_start' => '0xFFF7971E',
        'preview_gradient_end' => '0xFFFFD200',
        'preview_video_url' => '/media/templates/alps_sunrise.mp4',
        'preview_image_url' => '/media/templates/tmpl-golden-hour.jpg',
        'audio_title' => 'Cozy Family Acoustic',
        'audio_url' => '/media/templates/lofi_beat.wav',
        'tags' => 'Family,Home,Kids,Parents,Memories,Love',
        'is_pro' => 0,
        'is_trending' => 0,
        'is_new' => 1,
        'is_popular' => 0,
        'display_order' => 5,
        'slots' => [
            ['duration' => 3000, 'filter' => 'warm', 'transition' => 'fade', 'media' => 'assets/demo/ramen_bar.mp4'],
            ['duration' => 3000, 'filter' => 'softWarm', 'transition' => 'crossfade', 'media' => 'assets/demo/alps_sunrise.mp4'],
            ['duration' => 3000, 'filter' => 'vintage', 'transition' => 'fade', 'media' => 'assets/demo/sunset_beach.jpg'],
            ['duration' => 3000, 'filter' => 'warm', 'transition' => 'zoomIn', 'media' => 'assets/demo/tokyo_street.mp4'],
        ],
        'texts' => [
            ['text' => 'Family is Everything 🏡', 'font' => 'Inter', 'size' => 24, 'color' => 0xFFFFFFFF, 'bg' => 0xFFF7971E, 'start' => 0, 'end' => 6000, 'anim' => 'slideUp', 'x' => 0.5, 'y' => 0.2],
            ['text' => 'Unconditional Love', 'font' => 'SpaceMono', 'size' => 18, 'color' => 0xFFFFF8E1, 'bg' => null, 'start' => 6000, 'end' => 12000, 'anim' => 'typewriter', 'x' => 0.5, 'y' => 0.85],
        ]
    ],
    [
        'id' => 'tmpl-friends',
        'category' => 'Friends',
        'badge' => 'Squad',
        'title' => '👯 Best Friends Forever Vibe',
        'description' => 'High-energy snap cuts, retro film grain, quirky stickers, and punchy trap bounce.',
        'prompt' => 'Teen and college friends group road trip, singing along to music in car, selfie laughter bursts, beach campfire dancing.',
        'author' => 'Crew Visuals',
        'aspect_ratio' => 'ratio9_16',
        'duration_ms' => 10000,
        'clips_count' => 4,
        'downloads_count' => 38700,
        'preview_gradient_start' => '0xFFFF0844',
        'preview_gradient_end' => '0xFFFFB199',
        'preview_video_url' => '/media/templates/urban_skate.mp4',
        'preview_image_url' => '/media/templates/tmpl-urban-street.jpg',
        'audio_title' => 'Upbeat Squad Trap',
        'audio_url' => '/media/templates/urban_trap.wav',
        'tags' => 'Friends,Squad,Party,Vlog,Chill,Youth',
        'is_pro' => 0,
        'is_trending' => 1,
        'is_new' => 0,
        'is_popular' => 1,
        'display_order' => 6,
        'slots' => [
            ['duration' => 2500, 'filter' => 'vivid', 'transition' => 'slideLeft', 'media' => 'assets/demo/urban_skate.mp4'],
            ['duration' => 2500, 'filter' => 'punchy', 'transition' => 'zoomIn', 'media' => 'assets/demo/tokyo_shinjuku.mp4'],
            ['duration' => 2500, 'filter' => 'vintage', 'transition' => 'slideRight', 'media' => 'assets/demo/tokyo_street.mp4'],
            ['duration' => 2500, 'filter' => 'vivid', 'transition' => 'zoomIn', 'media' => 'assets/demo/cyberpunk_arcade.mp4'],
        ],
        'texts' => [
            ['text' => 'Squad Goals 🔥', 'font' => 'Inter', 'size' => 28, 'color' => 0xFFFFFFFF, 'bg' => 0xFFFF0844, 'start' => 0, 'end' => 5000, 'anim' => 'scale', 'x' => 0.5, 'y' => 0.2],
            ['text' => 'Best Memories 👯', 'font' => 'SpaceMono', 'size' => 20, 'color' => 0xFFFFE0B2, 'bg' => null, 'start' => 5000, 'end' => 10000, 'anim' => 'slideUp', 'x' => 0.5, 'y' => 0.82],
        ]
    ],
    [
        'id' => 'tmpl-birthday-slideshow',
        'category' => 'Birthday Slideshow',
        'badge' => 'Memories',
        'title' => '🎂 Memory Lane Birthday Slideshow',
        'description' => 'Elegant polaroid photo slides, memory year badges, smooth cross-fades, and uplifting pop.',
        'prompt' => 'Nostalgic photo collage montage celebrating growing up, childhood milestones, heartfelt congratulations message.',
        'author' => 'MemoryBox',
        'aspect_ratio' => 'ratio9_16',
        'duration_ms' => 15000,
        'clips_count' => 5,
        'downloads_count' => 26300,
        'preview_gradient_start' => '0xFF667EEA',
        'preview_gradient_end' => '0xFF764BA2',
        'preview_video_url' => '/media/templates/alps_sunrise.mp4',
        'preview_image_url' => '/media/templates/tmpl-golden-hour.jpg',
        'audio_title' => 'Celebration Melody',
        'audio_url' => '/media/templates/tropical_beat.wav',
        'tags' => 'Birthday,Slideshow,Photos,Memories,Years,Celebration',
        'is_pro' => 0,
        'is_trending' => 0,
        'is_new' => 1,
        'is_popular' => 0,
        'display_order' => 7,
        'slots' => [
            ['duration' => 3000, 'filter' => 'warm', 'transition' => 'fade', 'media' => 'assets/demo/sunset_beach.jpg'],
            ['duration' => 3000, 'filter' => 'softWarm', 'transition' => 'slideLeft', 'media' => 'assets/demo/alps_sunrise.mp4'],
            ['duration' => 3000, 'filter' => 'vintage', 'transition' => 'zoomIn', 'media' => 'assets/demo/ramen_bar.mp4'],
            ['duration' => 3000, 'filter' => 'warm', 'transition' => 'fade', 'media' => 'assets/demo/alps_drone.mp4'],
            ['duration' => 3000, 'filter' => 'vivid', 'transition' => 'slideRight', 'media' => 'assets/demo/tokyo_street.mp4'],
        ],
        'texts' => [
            ['text' => 'Years of Memories 🎈', 'font' => 'Inter', 'size' => 24, 'color' => 0xFFFFFFFF, 'bg' => 0xFF764BA2, 'start' => 0, 'end' => 7500, 'anim' => 'fade', 'x' => 0.5, 'y' => 0.18],
            ['text' => 'Cheers to Another Year! ✨', 'font' => 'SpaceMono', 'size' => 18, 'color' => 0xFFE1BEE7, 'bg' => null, 'start' => 7500, 'end' => 15000, 'anim' => 'typewriter', 'x' => 0.5, 'y' => 0.85],
        ]
    ],
    [
        'id' => 'tmpl-cinematic',
        'category' => 'Cinematic',
        'badge' => 'Masterpiece',
        'title' => '🎬 Hollywood 4K Cinematic Trailer',
        'description' => 'Wide 2.35:1 letterbox bars, teal & orange color grade, slow dramatic push-ins, and epic orchestral hits.',
        'prompt' => 'Anamorphic 2.39 aspect ratio movie teaser, dramatic rain soaked asphalt reflections, moody silhouette actor stepping into streetlight glow.',
        'author' => 'ProCut Studios',
        'aspect_ratio' => 'ratio16_9',
        'duration_ms' => 16000,
        'clips_count' => 4,
        'downloads_count' => 74200,
        'preview_gradient_start' => '0xFF0F2027',
        'preview_gradient_end' => '0xFF2C5364',
        'preview_video_url' => '/media/templates/alps_drone.mp4',
        'preview_image_url' => '/media/templates/tmpl-cinematic-youtube.jpg',
        'audio_title' => 'Epic Cinematic Horizon',
        'audio_url' => '/media/templates/cinematic_audio.wav',
        'tags' => 'Cinematic,Film,Trailer,Hollywood,Epic,TealOrange',
        'is_pro' => 1,
        'is_trending' => 1,
        'is_new' => 0,
        'is_popular' => 1,
        'display_order' => 8,
        'slots' => [
            ['duration' => 4000, 'filter' => 'cinematicTealOrange', 'transition' => 'fade', 'media' => 'assets/demo/alps_drone.mp4'],
            ['duration' => 4000, 'filter' => 'noir', 'transition' => 'crossfade', 'media' => 'assets/demo/alps_sunrise.mp4'],
            ['duration' => 4000, 'filter' => 'cinematicTealOrange', 'transition' => 'zoomIn', 'media' => 'assets/demo/tokyo_shinjuku.mp4'],
            ['duration' => 4000, 'filter' => 'darkMoody', 'transition' => 'fade', 'media' => 'assets/demo/cyberpunk_arcade.mp4'],
        ],
        'texts' => [
            ['text' => 'A PROCUT ORIGINAL FILM', 'font' => 'SpaceMono', 'size' => 20, 'color' => 0xFFECEFF1, 'bg' => 0xFF102027, 'start' => 0, 'end' => 8000, 'anim' => 'fade', 'x' => 0.5, 'y' => 0.2],
            ['text' => 'COMING SOON TO SCREENS', 'font' => 'Inter', 'size' => 24, 'color' => 0xFFFFAB00, 'bg' => null, 'start' => 8000, 'end' => 16000, 'anim' => 'typewriter', 'x' => 0.5, 'y' => 0.8],
        ]
    ],
    [
        'id' => 'tmpl-beat-sync',
        'category' => 'Beat Sync',
        'badge' => 'Bass Drop',
        'title' => '⚡ Ultra Beat Drop Sync',
        'description' => 'Clips snap to drum kick transients, shake on impact, strobe flash frames, and heavy 808 bass.',
        'prompt' => 'Hyper-aggressive beat match edit synced perfectly to 140 BPM phonk drop, hard flash frames and lens zoom impacts.',
        'author' => 'BassDrop FX',
        'aspect_ratio' => 'ratio9_16',
        'duration_ms' => 8000,
        'clips_count' => 5,
        'downloads_count' => 68900,
        'preview_gradient_start' => '0xFF8E2DE2',
        'preview_gradient_end' => '0xFF4A00E0',
        'preview_video_url' => '/media/templates/urban_skate.mp4',
        'preview_image_url' => '/media/templates/tmpl-viral-phonk.jpg',
        'audio_title' => 'Hardcore 808 Beat Drop',
        'audio_url' => '/media/templates/phonk_beat.wav',
        'tags' => 'BeatSync,Phonk,Bass,Drift,Rhythm,MusicSync',
        'is_pro' => 0,
        'is_trending' => 1,
        'is_new' => 0,
        'is_popular' => 1,
        'display_order' => 9,
        'slots' => [
            ['duration' => 1600, 'filter' => 'highContrast', 'transition' => 'zoomIn', 'media' => 'assets/demo/urban_skate.mp4'],
            ['duration' => 1600, 'filter' => 'punchy', 'transition' => 'glitch', 'media' => 'assets/demo/cyberpunk_arcade.mp4'],
            ['duration' => 1600, 'filter' => 'vivid', 'transition' => 'slideLeft', 'media' => 'assets/demo/tokyo_shinjuku.mp4'],
            ['duration' => 1600, 'filter' => 'highContrast', 'transition' => 'zoomIn', 'media' => 'assets/demo/tokyo_street.mp4'],
            ['duration' => 1600, 'filter' => 'punchy', 'transition' => 'glitch', 'media' => 'assets/demo/ramen_bar.mp4'],
        ],
        'texts' => [
            ['text' => 'DROP THE BASS ⚡', 'font' => 'Inter', 'size' => 30, 'color' => 0xFFFFFFFF, 'bg' => 0xFF8E2DE2, 'start' => 0, 'end' => 4000, 'anim' => 'scale', 'x' => 0.5, 'y' => 0.25],
            ['text' => '100% BEAT SYNC', 'font' => 'SpaceMono', 'size' => 20, 'color' => 0xFF00E5FF, 'bg' => null, 'start' => 4000, 'end' => 8000, 'anim' => 'slideUp', 'x' => 0.5, 'y' => 0.8],
        ]
    ],
    [
        'id' => 'tmpl-reels',
        'category' => 'Reels',
        'badge' => 'Viral',
        'title' => '📱 Trending Instagram Reel Edit',
        'description' => 'Punchy 3-second hook, auto-caption typography, snappy zoom-cuts, and viral audio.',
        'prompt' => 'High engagement vertical reel hook formula, split-screen attention grabber, captions popping up with bounce effect.',
        'author' => 'GrowthLab',
        'aspect_ratio' => 'ratio9_16',
        'duration_ms' => 9000,
        'clips_count' => 3,
        'downloads_count' => 59100,
        'preview_gradient_start' => '0xFFE1306C',
        'preview_gradient_end' => '0xFFF77737',
        'preview_video_url' => '/media/templates/tokyo_street.mp4',
        'preview_image_url' => '/media/templates/tmpl-hype-reel.jpg',
        'audio_title' => 'Viral Reels Hit',
        'audio_url' => '/media/templates/urban_trap.wav',
        'tags' => 'Reels,Instagram,TikTok,Viral,Growth,Hook',
        'is_pro' => 0,
        'is_trending' => 1,
        'is_new' => 1,
        'is_popular' => 1,
        'display_order' => 10,
        'slots' => [
            ['duration' => 3000, 'filter' => 'cleanPop', 'transition' => 'zoomIn', 'media' => 'assets/demo/tokyo_street.mp4'],
            ['duration' => 3000, 'filter' => 'vivid', 'transition' => 'slideLeft', 'media' => 'assets/demo/urban_skate.mp4'],
            ['duration' => 3000, 'filter' => 'punchy', 'transition' => 'zoomIn', 'media' => 'assets/demo/ramen_bar.mp4'],
        ],
        'texts' => [
            ['text' => 'WATCH TILL THE END 😱', 'font' => 'Inter', 'size' => 26, 'color' => 0xFFFFFFFF, 'bg' => 0xFFE1306C, 'start' => 0, 'end' => 4500, 'anim' => 'slideUp', 'x' => 0.5, 'y' => 0.18],
            ['text' => 'Share with your friends! 👇', 'font' => 'SpaceMono', 'size' => 18, 'color' => 0xFFFFF3E0, 'bg' => null, 'start' => 4500, 'end' => 9000, 'anim' => 'typewriter', 'x' => 0.5, 'y' => 0.82],
        ]
    ],
    [
        'id' => 'tmpl-festival',
        'category' => 'Festival',
        'badge' => 'Celebration',
        'title' => '🎆 Festival & Holiday Spark',
        'description' => 'Golden sparkles, firework overlays, rich celebratory colors, and festive orchestral bells.',
        'prompt' => 'Grand night fireworks bursting over crowded city square, cheering crowds waving sparklers, vibrant festive colors.',
        'author' => 'Festive Sparks',
        'aspect_ratio' => 'ratio9_16',
        'duration_ms' => 12000,
        'clips_count' => 4,
        'downloads_count' => 31200,
        'preview_gradient_start' => '0xFFFF512F',
        'preview_gradient_end' => '0xFFDD2476',
        'preview_video_url' => '/media/templates/tokyo_shinjuku.mp4',
        'preview_image_url' => '/media/templates/tmpl-golden-hour.jpg',
        'audio_title' => 'Festival Joy Beats',
        'audio_url' => '/media/templates/tropical_beat.wav',
        'tags' => 'Festival,Celebration,Holidays,Fireworks,NewYear,Lights',
        'is_pro' => 0,
        'is_trending' => 0,
        'is_new' => 1,
        'is_popular' => 1,
        'display_order' => 11,
        'slots' => [
            ['duration' => 3000, 'filter' => 'vibrant', 'transition' => 'zoomIn', 'media' => 'assets/demo/tokyo_shinjuku.mp4'],
            ['duration' => 3000, 'filter' => 'warm', 'transition' => 'fade', 'media' => 'assets/demo/alps_sunrise.mp4'],
            ['duration' => 3000, 'filter' => 'vivid', 'transition' => 'zoomIn', 'media' => 'assets/demo/cyberpunk_arcade.mp4'],
            ['duration' => 3000, 'filter' => 'vibrant', 'transition' => 'crossfade', 'media' => 'assets/demo/sunset_beach.jpg'],
        ],
        'texts' => [
            ['text' => 'HAPPY FESTIVAL! 🎆', 'font' => 'Inter', 'size' => 28, 'color' => 0xFFFFFFFF, 'bg' => 0xFFDD2476, 'start' => 0, 'end' => 6000, 'anim' => 'scale', 'x' => 0.5, 'y' => 0.22],
            ['text' => 'Light & Prosperity ✨', 'font' => 'SpaceMono', 'size' => 20, 'color' => 0xFFFFE082, 'bg' => null, 'start' => 6000, 'end' => 12000, 'anim' => 'fade', 'x' => 0.5, 'y' => 0.85],
        ]
    ],
    [
        'id' => 'tmpl-graduation',
        'category' => 'Graduation',
        'badge' => 'Achievement',
        'title' => '🎓 Class of Success Graduation Film',
        'description' => 'Inspiring journey timeline, diploma cap throw keyframes, proud typography, and triumphant brass.',
        'prompt' => 'Graduation commencement day ceremony, mortarboards thrown into blue sky in slow-motion, tearful proud hugs.',
        'author' => 'Campus Moments',
        'aspect_ratio' => 'ratio9_16',
        'duration_ms' => 14000,
        'clips_count' => 4,
        'downloads_count' => 24800,
        'preview_gradient_start' => '0xFF1D976C',
        'preview_gradient_end' => '0xFF93F9B9',
        'preview_video_url' => '/media/templates/alps_drone.mp4',
        'preview_image_url' => '/media/templates/tmpl-summer-tropical.jpg',
        'audio_title' => 'Triumphant March Score',
        'audio_url' => '/media/templates/cinematic_audio.wav',
        'tags' => 'Graduation,College,School,Diploma,Success,Future',
        'is_pro' => 0,
        'is_trending' => 0,
        'is_new' => 1,
        'is_popular' => 0,
        'display_order' => 12,
        'slots' => [
            ['duration' => 3500, 'filter' => 'warm', 'transition' => 'fade', 'media' => 'assets/demo/alps_sunrise.mp4'],
            ['duration' => 3500, 'filter' => 'cleanPop', 'transition' => 'slideUp', 'media' => 'assets/demo/alps_drone.mp4'],
            ['duration' => 3500, 'filter' => 'goldenHour', 'transition' => 'fade', 'media' => 'assets/demo/sunset_beach.jpg'],
            ['duration' => 3500, 'filter' => 'warm', 'transition' => 'zoomIn', 'media' => 'assets/demo/ramen_bar.mp4'],
        ],
        'texts' => [
            ['text' => 'WE MADE IT! 🎓', 'font' => 'Inter', 'size' => 30, 'color' => 0xFFFFFFFF, 'bg' => 0xFF1D976C, 'start' => 0, 'end' => 7000, 'anim' => 'slideUp', 'x' => 0.5, 'y' => 0.2],
            ['text' => 'Class of 2026 🥂', 'font' => 'SpaceMono', 'size' => 22, 'color' => 0xFFE8F5E9, 'bg' => null, 'start' => 7000, 'end' => 14000, 'anim' => 'typewriter', 'x' => 0.5, 'y' => 0.85],
        ]
    ],
    [
        'id' => 'tmpl-before-after',
        'category' => 'Before & After',
        'badge' => 'Transformation',
        'title' => '🔄 Before & After Split Transformation',
        'description' => 'Wipe transition comparing original raw state to finished transformation, with split title badges.',
        'prompt' => 'Dramatic side by side before and after transition, split wipe reveals stunning interior renovation makeover.',
        'author' => 'TransformLab',
        'aspect_ratio' => 'ratio9_16',
        'duration_ms' => 10000,
        'clips_count' => 2,
        'downloads_count' => 45600,
        'preview_gradient_start' => '0xFF11998E',
        'preview_gradient_end' => '0xFF38EF7D',
        'preview_video_url' => '/media/templates/tokyo_street.mp4',
        'preview_image_url' => '/media/templates/tmpl-urban-street.jpg',
        'audio_title' => 'Bass Hit Reveal',
        'audio_url' => '/media/templates/urban_trap.wav',
        'tags' => 'BeforeAfter,Transformation,Makeover,Fitness,Design,Reveal',
        'is_pro' => 0,
        'is_trending' => 1,
        'is_new' => 0,
        'is_popular' => 1,
        'display_order' => 13,
        'slots' => [
            ['duration' => 5000, 'filter' => 'noir', 'transition' => 'fade', 'media' => 'assets/demo/tokyo_street.mp4'],
            ['duration' => 5000, 'filter' => 'vivid', 'transition' => 'wipeRight', 'media' => 'assets/demo/tokyo_shinjuku.mp4'],
        ],
        'texts' => [
            ['text' => 'BEFORE ⬅️', 'font' => 'Inter', 'size' => 26, 'color' => 0xFFB0BEC5, 'bg' => 0xFF263238, 'start' => 0, 'end' => 5000, 'anim' => 'slideLeft', 'x' => 0.5, 'y' => 0.2],
            ['text' => 'AFTER ➡️ ✨', 'font' => 'Inter', 'size' => 28, 'color' => 0xFFFFFFFF, 'bg' => 0xFF11998E, 'start' => 5000, 'end' => 10000, 'anim' => 'scale', 'x' => 0.5, 'y' => 0.2],
        ]
    ],
    [
        'id' => 'tmpl-80s-retro',
        'category' => '80s Retro',
        'badge' => 'Synthwave',
        'title' => '📼 1985 Synthwave Retro VHS',
        'description' => 'CRT scanlines, tape glitch, neon grid title typography, and pulsing analog synthesizer chords.',
        'prompt' => 'Retro 1985 VHS magnetic tape distortion, glowing wireframe purple horizon grid, chrome typography reflections.',
        'author' => 'Radical 80s',
        'aspect_ratio' => 'ratio9_16',
        'duration_ms' => 12000,
        'clips_count' => 4,
        'downloads_count' => 53400,
        'preview_gradient_start' => '0xFFFF007F',
        'preview_gradient_end' => '0xFF7928CA',
        'preview_video_url' => '/media/templates/cyberpunk_arcade.mp4',
        'preview_image_url' => '/media/templates/tmpl-retro-90s.jpg',
        'audio_title' => 'Analog Synth Neon Drive',
        'audio_url' => '/media/templates/synthwave_beat.wav',
        'tags' => '80s,Retro,Synthwave,VHS,Neon,Glitch,Vintage',
        'is_pro' => 0,
        'is_trending' => 1,
        'is_new' => 0,
        'is_popular' => 1,
        'display_order' => 14,
        'slots' => [
            ['duration' => 3000, 'filter' => 'vhsGlitch', 'transition' => 'glitch', 'media' => 'assets/demo/cyberpunk_arcade.mp4'],
            ['duration' => 3000, 'filter' => 'vintage', 'transition' => 'fade', 'media' => 'assets/demo/tokyo_shinjuku.mp4'],
            ['duration' => 3000, 'filter' => 'vhsGlitch', 'transition' => 'zoomIn', 'media' => 'assets/demo/urban_skate.mp4'],
            ['duration' => 3000, 'filter' => 'vintage', 'transition' => 'glitch', 'media' => 'assets/demo/ramen_bar.mp4'],
        ],
        'texts' => [
            ['text' => 'PLAY ▶ 00:19:85', 'font' => 'SpaceMono', 'size' => 22, 'color' => 0xFF00FF66, 'bg' => 0xFF120024, 'start' => 0, 'end' => 6000, 'anim' => 'typewriter', 'x' => 0.5, 'y' => 0.15],
            ['text' => 'RETRO WAVE ⚡', 'font' => 'Inter', 'size' => 28, 'color' => 0xFFFF007F, 'bg' => null, 'start' => 6000, 'end' => 12000, 'anim' => 'scale', 'x' => 0.5, 'y' => 0.82],
        ]
    ],
    [
        'id' => 'tmpl-trending',
        'category' => 'Trending',
        'badge' => 'Top #1',
        'title' => '🔥 Global Trending FYP Sensation',
        'description' => 'The #1 trending sound with synchronized micro-shakes, speed ramps, and bold kinetic text.',
        'prompt' => 'Global viral TikTok sensation edit, ultra crisp framing, fast cut transitions on every rhythm kick, vibrant lighting.',
        'author' => 'Viral King',
        'aspect_ratio' => 'ratio9_16',
        'duration_ms' => 11000,
        'clips_count' => 4,
        'downloads_count' => 89300,
        'preview_gradient_start' => '0xFFFF416C',
        'preview_gradient_end' => '0xFFFF4B2B',
        'preview_video_url' => '/media/templates/urban_skate.mp4',
        'preview_image_url' => '/media/templates/tmpl-viral-phonk.jpg',
        'audio_title' => 'FYP Anthem Beats',
        'audio_url' => '/media/templates/phonk_beat.wav',
        'tags' => 'Trending,Viral,FYP,Explore,Popular,Top',
        'is_pro' => 0,
        'is_trending' => 1,
        'is_new' => 0,
        'is_popular' => 1,
        'display_order' => 15,
        'slots' => [
            ['duration' => 2750, 'filter' => 'punchy', 'transition' => 'zoomIn', 'media' => 'assets/demo/urban_skate.mp4'],
            ['duration' => 2750, 'filter' => 'vivid', 'transition' => 'slideLeft', 'media' => 'assets/demo/tokyo_shinjuku.mp4'],
            ['duration' => 2750, 'filter' => 'cleanPop', 'transition' => 'zoomIn', 'media' => 'assets/demo/ramen_bar.mp4'],
            ['duration' => 2750, 'filter' => 'punchy', 'transition' => 'fade', 'media' => 'assets/demo/cyberpunk_arcade.mp4'],
        ],
        'texts' => [
            ['text' => 'TRENDING NOW 🔥', 'font' => 'Inter', 'size' => 30, 'color' => 0xFFFFFFFF, 'bg' => 0xFFFF416C, 'start' => 0, 'end' => 5500, 'anim' => 'scale', 'x' => 0.5, 'y' => 0.2],
            ['text' => '#FYP #ViralVideo', 'font' => 'SpaceMono', 'size' => 20, 'color' => 0xFFFFCDD2, 'bg' => null, 'start' => 5500, 'end' => 11000, 'anim' => 'slideUp', 'x' => 0.5, 'y' => 0.85],
        ]
    ],
    [
        'id' => 'tmpl-photo-memories',
        'category' => 'Photo Memories',
        'badge' => 'Polaroid',
        'title' => '📷 Polaroid Photo Memories Scrapbook',
        'description' => 'Camera flash impacts, polaroid frame borders, handwritten font titles, and warm memories.',
        'prompt' => 'Vintage scrapbook page turning with candid polaroid pictures, tape corners, soft acoustic guitar soundtrack.',
        'author' => 'Scrapbook Arts',
        'aspect_ratio' => 'ratio9_16',
        'duration_ms' => 15000,
        'clips_count' => 5,
        'downloads_count' => 37400,
        'preview_gradient_start' => '0xFF834D9B',
        'preview_gradient_end' => '0xFFD04ED6',
        'preview_video_url' => '/media/templates/alps_sunrise.mp4',
        'preview_image_url' => '/media/templates/tmpl-golden-hour.jpg',
        'audio_title' => 'Lo-Fi Polaroid Nostalgia',
        'audio_url' => '/media/templates/lofi_beat.wav',
        'tags' => 'Photo,Memories,Polaroid,Scrapbook,Nostalgia,Vintage',
        'is_pro' => 0,
        'is_trending' => 0,
        'is_new' => 1,
        'is_popular' => 1,
        'display_order' => 16,
        'slots' => [
            ['duration' => 3000, 'filter' => 'vintage', 'transition' => 'fade', 'media' => 'assets/demo/sunset_beach.jpg'],
            ['duration' => 3000, 'filter' => 'warm', 'transition' => 'slideRight', 'media' => 'assets/demo/alps_sunrise.mp4'],
            ['duration' => 3000, 'filter' => 'vintage', 'transition' => 'fade', 'media' => 'assets/demo/ramen_bar.mp4'],
            ['duration' => 3000, 'filter' => 'softWarm', 'transition' => 'slideLeft', 'media' => 'assets/demo/tokyo_street.mp4'],
            ['duration' => 3000, 'filter' => 'vintage', 'transition' => 'zoomIn', 'media' => 'assets/demo/alps_drone.mp4'],
        ],
        'texts' => [
            ['text' => 'Golden Days 📸', 'font' => 'Inter', 'size' => 26, 'color' => 0xFFFFFFFF, 'bg' => 0xFF834D9B, 'start' => 0, 'end' => 7500, 'anim' => 'fade', 'x' => 0.5, 'y' => 0.2],
            ['text' => 'Unforgettable Moments', 'font' => 'SpaceMono', 'size' => 18, 'color' => 0xFFF3E5F5, 'bg' => null, 'start' => 7500, 'end' => 15000, 'anim' => 'typewriter', 'x' => 0.5, 'y' => 0.85],
        ]
    ],
    [
        'id' => 'tmpl-fashion',
        'category' => 'Fashion',
        'badge' => 'Editorial',
        'title' => '👠 High Fashion Runway Lookbook',
        'description' => 'Editorial magazine split grids, strobe flash frames, clean serif typography, and deep house runway bass.',
        'prompt' => 'High fashion runway catwalk model in designer haute couture garment, strobe camera flash bursts, sleek minimalist typography.',
        'author' => 'Atelier Visuals',
        'aspect_ratio' => 'ratio9_16',
        'duration_ms' => 11000,
        'clips_count' => 4,
        'downloads_count' => 42900,
        'preview_gradient_start' => '0xFF232526',
        'preview_gradient_end' => '0xFF414345',
        'preview_video_url' => '/media/templates/tokyo_street.mp4',
        'preview_image_url' => '/media/templates/tmpl-urban-street.jpg',
        'audio_title' => 'Deep House Runway Groove',
        'audio_url' => '/media/templates/urban_trap.wav',
        'tags' => 'Fashion,Lookbook,OOTD,Runway,Vogue,Model,Style',
        'is_pro' => 1,
        'is_trending' => 1,
        'is_new' => 0,
        'is_popular' => 1,
        'display_order' => 17,
        'slots' => [
            ['duration' => 2750, 'filter' => 'noir', 'transition' => 'slideLeft', 'media' => 'assets/demo/tokyo_street.mp4'],
            ['duration' => 2750, 'filter' => 'highContrast', 'transition' => 'zoomIn', 'media' => 'assets/demo/tokyo_shinjuku.mp4'],
            ['duration' => 2750, 'filter' => 'noir', 'transition' => 'fade', 'media' => 'assets/demo/urban_skate.mp4'],
            ['duration' => 2750, 'filter' => 'cleanPop', 'transition' => 'zoomIn', 'media' => 'assets/demo/ramen_bar.mp4'],
        ],
        'texts' => [
            ['text' => 'VOGUE LOOKBOOK 👠', 'font' => 'Inter', 'size' => 26, 'color' => 0xFFFFFFFF, 'bg' => 0xFF111111, 'start' => 0, 'end' => 5500, 'anim' => 'slideUp', 'x' => 0.5, 'y' => 0.2],
            ['text' => 'SPRING / SUMMER 2026', 'font' => 'SpaceMono', 'size' => 16, 'color' => 0xFFE0E0E0, 'bg' => null, 'start' => 5500, 'end' => 11000, 'anim' => 'typewriter', 'x' => 0.5, 'y' => 0.85],
        ]
    ],
    [
        'id' => 'tmpl-celebration',
        'category' => 'Celebration',
        'badge' => 'Party',
        'title' => '🥂 Grand Celebration & Victory Party',
        'description' => 'Champagne pop sound triggers, golden ribbon overlays, celebratory badges, and energetic party house.',
        'prompt' => 'Grand victory celebration event, champagne toast spray under disco lights, smiling friends jumping together.',
        'author' => 'Fiesta Media',
        'aspect_ratio' => 'ratio9_16',
        'duration_ms' => 12000,
        'clips_count' => 4,
        'downloads_count' => 33100,
        'preview_gradient_start' => '0xFFF12711',
        'preview_gradient_end' => '0xFFF5AF19',
        'preview_video_url' => '/media/templates/tokyo_shinjuku.mp4',
        'preview_image_url' => '/media/templates/tmpl-golden-hour.jpg',
        'audio_title' => 'Celebration Anthem Beat',
        'audio_url' => '/media/templates/tropical_beat.wav',
        'tags' => 'Celebration,Party,Cheers,Victory,Champagne,Fun',
        'is_pro' => 0,
        'is_trending' => 0,
        'is_new' => 1,
        'is_popular' => 1,
        'display_order' => 18,
        'slots' => [
            ['duration' => 3000, 'filter' => 'warm', 'transition' => 'zoomIn', 'media' => 'assets/demo/tokyo_shinjuku.mp4'],
            ['duration' => 3000, 'filter' => 'vivid', 'transition' => 'fade', 'media' => 'assets/demo/ramen_bar.mp4'],
            ['duration' => 3000, 'filter' => 'punchy', 'transition' => 'slideRight', 'media' => 'assets/demo/urban_skate.mp4'],
            ['duration' => 3000, 'filter' => 'warm', 'transition' => 'zoomIn', 'media' => 'assets/demo/sunset_beach.jpg'],
        ],
        'texts' => [
            ['text' => 'CELEBRATE TODAY 🥂', 'font' => 'Inter', 'size' => 28, 'color' => 0xFFFFFFFF, 'bg' => 0xFFF12711, 'start' => 0, 'end' => 6000, 'anim' => 'scale', 'x' => 0.5, 'y' => 0.22],
            ['text' => 'Victory & Good Vibes ✨', 'font' => 'SpaceMono', 'size' => 18, 'color' => 0xFFFFF8E1, 'bg' => null, 'start' => 6000, 'end' => 12000, 'anim' => 'slideUp', 'x' => 0.5, 'y' => 0.85],
        ]
    ],
    [
        'id' => 'tmpl-business',
        'category' => 'Business',
        'badge' => 'Corporate',
        'title' => '💼 Corporate Startup Pitch & Showcase',
        'description' => 'Clean professional lower-thirds, corporate blue grading, minimal kinetic typography, and inspiring piano.',
        'prompt' => 'Sleek corporate tech startup showcase, glass skyscraper office, engineers collaborating over laptops, clean data graphs.',
        'author' => 'Venture Media',
        'aspect_ratio' => 'ratio16_9',
        'duration_ms' => 15000,
        'clips_count' => 4,
        'downloads_count' => 27800,
        'preview_gradient_start' => '0xFF1E3C72',
        'preview_gradient_end' => '0xFF2A5298',
        'preview_video_url' => '/media/templates/alps_drone.mp4',
        'preview_image_url' => '/media/templates/tmpl-cinematic-youtube.jpg',
        'audio_title' => 'Corporate Inspiration Piano',
        'audio_url' => '/media/templates/cinematic_audio.wav',
        'tags' => 'Business,Corporate,Startup,Enterprise,Presentation,Tech',
        'is_pro' => 1,
        'is_trending' => 0,
        'is_new' => 1,
        'is_popular' => 0,
        'display_order' => 19,
        'slots' => [
            ['duration' => 3750, 'filter' => 'cleanBlue', 'transition' => 'slideLeft', 'media' => 'assets/demo/alps_drone.mp4'],
            ['duration' => 3750, 'filter' => 'cleanPop', 'transition' => 'fade', 'media' => 'assets/demo/tokyo_street.mp4'],
            ['duration' => 3750, 'filter' => 'cleanBlue', 'transition' => 'crossfade', 'media' => 'assets/demo/ramen_bar.mp4'],
            ['duration' => 3750, 'filter' => 'cinematicTealOrange', 'transition' => 'zoomIn', 'media' => 'assets/demo/tokyo_shinjuku.mp4'],
        ],
        'texts' => [
            ['text' => 'INNOVATION REDEFINED 💼', 'font' => 'Inter', 'size' => 24, 'color' => 0xFFFFFFFF, 'bg' => 0xFF1E3C72, 'start' => 0, 'end' => 7500, 'anim' => 'slideUp', 'x' => 0.5, 'y' => 0.18],
            ['text' => 'Building The Future Together', 'font' => 'SpaceMono', 'size' => 18, 'color' => 0xFFBBDEFB, 'bg' => null, 'start' => 7500, 'end' => 15000, 'anim' => 'typewriter', 'x' => 0.5, 'y' => 0.82],
        ]
    ],
    [
        'id' => 'tmpl-motivation',
        'category' => 'Motivation',
        'badge' => 'Grind',
        'title' => '🦁 Daily Motivation & Mindset Grind',
        'description' => 'Deep voiceover cadence pauses, intense contrast grading, gritty camera shakes, and relentless build-up.',
        'prompt' => 'Intense motivational athlete training at 5 AM in empty stadium, heavy breathing condensation in cold air, unstoppable focus.',
        'author' => 'Mindset Pro',
        'aspect_ratio' => 'ratio9_16',
        'duration_ms' => 13000,
        'clips_count' => 4,
        'downloads_count' => 54100,
        'preview_gradient_start' => '0xFF283048',
        'preview_gradient_end' => '0xFF859398',
        'preview_video_url' => '/media/templates/urban_skate.mp4',
        'preview_image_url' => '/media/templates/tmpl-hype-reel.jpg',
        'audio_title' => 'Relentless Grind Score',
        'audio_url' => '/media/templates/cinematic_audio.wav',
        'tags' => 'Motivation,Mindset,Grind,Focus,Discipline,Success',
        'is_pro' => 0,
        'is_trending' => 1,
        'is_new' => 0,
        'is_popular' => 1,
        'display_order' => 20,
        'slots' => [
            ['duration' => 3250, 'filter' => 'darkMoody', 'transition' => 'zoomIn', 'media' => 'assets/demo/urban_skate.mp4'],
            ['duration' => 3250, 'filter' => 'highContrast', 'transition' => 'fade', 'media' => 'assets/demo/cyberpunk_arcade.mp4'],
            ['duration' => 3250, 'filter' => 'noir', 'transition' => 'slideLeft', 'media' => 'assets/demo/tokyo_shinjuku.mp4'],
            ['duration' => 3250, 'filter' => 'darkMoody', 'transition' => 'zoomIn', 'media' => 'assets/demo/alps_drone.mp4'],
        ],
        'texts' => [
            ['text' => 'NEVER GIVE UP 🦁', 'font' => 'Inter', 'size' => 30, 'color' => 0xFFFFFFFF, 'bg' => 0xFF212121, 'start' => 0, 'end' => 6500, 'anim' => 'scale', 'x' => 0.5, 'y' => 0.2],
            ['text' => 'Discipline Over Motivation', 'font' => 'SpaceMono', 'size' => 18, 'color' => 0xFFFFD54F, 'bg' => null, 'start' => 6500, 'end' => 13000, 'anim' => 'slideUp', 'x' => 0.5, 'y' => 0.85],
        ]
    ],
    [
        'id' => 'tmpl-nature',
        'category' => 'Nature',
        'badge' => 'Serenity',
        'title' => '🌿 Earth & Nature Wild Sanctuary',
        'description' => 'Lush emerald green saturation, slow cinematic pan & zoom keyframes, tranquil bird ambience, and ambient pads.',
        'prompt' => 'Untouched alpine wilderness aerial drone glide, crystal glacier lake reflecting pine forest and snow-capped peaks.',
        'author' => 'Earth Sanctuary',
        'aspect_ratio' => 'ratio16_9',
        'duration_ms' => 16000,
        'clips_count' => 4,
        'downloads_count' => 41500,
        'preview_gradient_start' => '0xFF134E5E',
        'preview_gradient_end' => '0xFF71B280',
        'preview_video_url' => '/media/templates/alps_drone.mp4',
        'preview_image_url' => '/media/templates/tmpl-cinematic-youtube.jpg',
        'audio_title' => 'Forest Ambient Waves',
        'audio_url' => '/media/templates/lofi_beat.wav',
        'tags' => 'Nature,Wild,Mountains,Forest,Peaceful,Earth',
        'is_pro' => 0,
        'is_trending' => 0,
        'is_new' => 1,
        'is_popular' => 1,
        'display_order' => 21,
        'slots' => [
            ['duration' => 4000, 'filter' => 'vibrant', 'transition' => 'fade', 'media' => 'assets/demo/alps_drone.mp4'],
            ['duration' => 4000, 'filter' => 'warm', 'transition' => 'crossfade', 'media' => 'assets/demo/alps_sunrise.mp4'],
            ['duration' => 4000, 'filter' => 'vivid', 'transition' => 'fade', 'media' => 'assets/demo/sunset_beach.jpg'],
            ['duration' => 4000, 'filter' => 'vibrant', 'transition' => 'zoomIn', 'media' => 'assets/demo/ramen_bar.mp4'],
        ],
        'texts' => [
            ['text' => 'EARTH SANCTUARY 🌿', 'font' => 'Inter', 'size' => 26, 'color' => 0xFFFFFFFF, 'bg' => 0xFF134E5E, 'start' => 0, 'end' => 8000, 'anim' => 'fade', 'x' => 0.5, 'y' => 0.2],
            ['text' => 'Breathe & Reconnect With Nature', 'font' => 'SpaceMono', 'size' => 18, 'color' => 0xFFC8E6C9, 'bg' => null, 'start' => 8000, 'end' => 16000, 'anim' => 'typewriter', 'x' => 0.5, 'y' => 0.82],
        ]
    ],
    [
        'id' => 'tmpl-food',
        'category' => 'Food',
        'badge' => 'Delicious',
        'title' => '🍜 Gourmet Food & Culinary Feast',
        'description' => 'Sizzling sizzle-reel cuts, mouth-watering warm color boosts, recipe step overlays, and cheerful acoustic bounce.',
        'prompt' => 'Steaming authentic ramen bowl garnishing with fresh green onions and marinated egg yolk dripping in slow motion.',
        'author' => 'Taste Bites',
        'aspect_ratio' => 'ratio9_16',
        'duration_ms' => 12000,
        'clips_count' => 4,
        'downloads_count' => 48200,
        'preview_gradient_start' => '0xFFFF8008',
        'preview_gradient_end' => '0xFFFFC837',
        'preview_video_url' => '/media/templates/ramen_bar.mp4',
        'preview_image_url' => '/media/templates/tmpl-golden-hour.jpg',
        'audio_title' => 'Kitchen Cooking Groove',
        'audio_url' => '/media/templates/tropical_beat.wav',
        'tags' => 'Food,Recipe,Cooking,Gourmet,Restaurant,Delicious',
        'is_pro' => 0,
        'is_trending' => 1,
        'is_new' => 0,
        'is_popular' => 1,
        'display_order' => 22,
        'slots' => [
            ['duration' => 3000, 'filter' => 'warm', 'transition' => 'zoomIn', 'media' => 'assets/demo/ramen_bar.mp4'],
            ['duration' => 3000, 'filter' => 'vivid', 'transition' => 'slideLeft', 'media' => 'assets/demo/tokyo_shinjuku.mp4'],
            ['duration' => 3000, 'filter' => 'punchy', 'transition' => 'zoomIn', 'media' => 'assets/demo/tokyo_street.mp4'],
            ['duration' => 3000, 'filter' => 'warm', 'transition' => 'fade', 'media' => 'assets/demo/sunset_beach.jpg'],
        ],
        'texts' => [
            ['text' => "CHEF'S SPECIAL 🍜", 'font' => 'Inter', 'size' => 28, 'color' => 0xFFFFFFFF, 'bg' => 0xFFFF8008, 'start' => 0, 'end' => 6000, 'anim' => 'slideUp', 'x' => 0.5, 'y' => 0.2],
            ['text' => 'Recipe Ingredients Below 👇', 'font' => 'SpaceMono', 'size' => 18, 'color' => 0xFFFFF8E1, 'bg' => null, 'start' => 6000, 'end' => 12000, 'anim' => 'typewriter', 'x' => 0.5, 'y' => 0.85],
        ]
    ],
    [
        'id' => 'tmpl-fitness',
        'category' => 'Fitness',
        'badge' => 'Intensity',
        'title' => '💪 High Intensity Gym & Workout Reel',
        'description' => 'Heart-pumping BPM sync, monochrome high-contrast grading, explosive zoom impacts on reps.',
        'prompt' => 'Dark high-contrast underground gym session, bodybuilder deadlift lift chalk cloud explosion, intense muscle strain.',
        'author' => 'Iron Club',
        'aspect_ratio' => 'ratio9_16',
        'duration_ms' => 10000,
        'clips_count' => 4,
        'downloads_count' => 51200,
        'preview_gradient_start' => '0xFFED213A',
        'preview_gradient_end' => '0xFF93291E',
        'preview_video_url' => '/media/templates/urban_skate.mp4',
        'preview_image_url' => '/media/templates/tmpl-hype-reel.jpg',
        'audio_title' => 'High BPM Gym Motivation',
        'audio_url' => '/media/templates/phonk_beat.wav',
        'tags' => 'Fitness,Gym,Workout,Bodybuilding,Crossfit,Sweat',
        'is_pro' => 0,
        'is_trending' => 1,
        'is_new' => 0,
        'is_popular' => 1,
        'display_order' => 23,
        'slots' => [
            ['duration' => 2500, 'filter' => 'highContrast', 'transition' => 'zoomIn', 'media' => 'assets/demo/urban_skate.mp4'],
            ['duration' => 2500, 'filter' => 'noir', 'transition' => 'glitch', 'media' => 'assets/demo/cyberpunk_arcade.mp4'],
            ['duration' => 2500, 'filter' => 'punchy', 'transition' => 'slideLeft', 'media' => 'assets/demo/tokyo_shinjuku.mp4'],
            ['duration' => 2500, 'filter' => 'highContrast', 'transition' => 'zoomIn', 'media' => 'assets/demo/tokyo_street.mp4'],
        ],
        'texts' => [
            ['text' => 'NO PAIN NO GAIN 💪', 'font' => 'Inter', 'size' => 28, 'color' => 0xFFFFFFFF, 'bg' => 0xFFED213A, 'start' => 0, 'end' => 5000, 'anim' => 'scale', 'x' => 0.5, 'y' => 0.2],
            ['text' => 'Daily Workout Routine 🔥', 'font' => 'SpaceMono', 'size' => 18, 'color' => 0xFFFFCDD2, 'bg' => null, 'start' => 5000, 'end' => 10000, 'anim' => 'slideUp', 'x' => 0.5, 'y' => 0.85],
        ]
    ],
    [
        'id' => 'tmpl-fast-transitions',
        'category' => 'Fast Transitions',
        'badge' => 'Turbo',
        'title' => '⚡ Rapid Whip & Zoom Cut Showcase',
        'description' => 'Supercharged 0.5s whip-pans, snap-zooms, warp-cuts, seamless continuous motion.',
        'prompt' => 'Rapid whip pan camera transitions connecting different city skylines in seamless non-stop continuous kinetic flow.',
        'author' => 'Motion Warp',
        'aspect_ratio' => 'ratio9_16',
        'duration_ms' => 8000,
        'clips_count' => 5,
        'downloads_count' => 63700,
        'preview_gradient_start' => '0xFFFC5C7D',
        'preview_gradient_end' => '0xFF6A82FB',
        'preview_video_url' => '/media/templates/tokyo_shinjuku.mp4',
        'preview_image_url' => '/media/templates/tmpl-urban-street.jpg',
        'audio_title' => 'Rapid Snap Bounce Beat',
        'audio_url' => '/media/templates/urban_trap.wav',
        'tags' => 'FastTransitions,WhipPan,ZoomCut,Kinetic,SpeedRamp,Edits',
        'is_pro' => 1,
        'is_trending' => 1,
        'is_new' => 1,
        'is_popular' => 1,
        'display_order' => 24,
        'slots' => [
            ['duration' => 1600, 'filter' => 'vivid', 'transition' => 'zoomIn', 'media' => 'assets/demo/tokyo_shinjuku.mp4'],
            ['duration' => 1600, 'filter' => 'punchy', 'transition' => 'slideLeft', 'media' => 'assets/demo/urban_skate.mp4'],
            ['duration' => 1600, 'filter' => 'cleanPop', 'transition' => 'slideRight', 'media' => 'assets/demo/tokyo_street.mp4'],
            ['duration' => 1600, 'filter' => 'vivid', 'transition' => 'zoomIn', 'media' => 'assets/demo/cyberpunk_arcade.mp4'],
            ['duration' => 1600, 'filter' => 'punchy', 'transition' => 'glitch', 'media' => 'assets/demo/ramen_bar.mp4'],
        ],
        'texts' => [
            ['text' => 'SPEED RUN ⚡', 'font' => 'Inter', 'size' => 30, 'color' => 0xFFFFFFFF, 'bg' => 0xFFFC5C7D, 'start' => 0, 'end' => 4000, 'anim' => 'scale', 'x' => 0.5, 'y' => 0.22],
            ['text' => 'Seamless Visual Flow', 'font' => 'SpaceMono', 'size' => 18, 'color' => 0xFFE8EAF6, 'bg' => null, 'start' => 4000, 'end' => 8000, 'anim' => 'slideUp', 'x' => 0.5, 'y' => 0.82],
        ]
    ],
    [
        'id' => 'tmpl-viral-short',
        'category' => 'Viral/Short Video',
        'badge' => 'Retention',
        'title' => '🚀 10-Second Viral Short Video',
        'description' => 'Engineered for 100%+ viewer retention with 0.8s hook, animated captions, looping ending transition.',
        'prompt' => 'High retention viral short video format, dynamic sound effect markers, looping visual cliffhanger ending.',
        'author' => 'Shorts Master',
        'aspect_ratio' => 'ratio9_16',
        'duration_ms' => 10000,
        'clips_count' => 3,
        'downloads_count' => 78200,
        'preview_gradient_start' => '0xFF00C9FF',
        'preview_gradient_end' => '0xFF92FE9D',
        'preview_video_url' => '/media/templates/urban_skate.mp4',
        'preview_image_url' => '/media/templates/tmpl-viral-phonk.jpg',
        'audio_title' => 'Viral Loop Audio Track',
        'audio_url' => '/media/templates/phonk_beat.wav',
        'tags' => 'Viral,Shorts,Retention,Loop,YouTubeShorts,Reels',
        'is_pro' => 0,
        'is_trending' => 1,
        'is_new' => 1,
        'is_popular' => 1,
        'display_order' => 25,
        'slots' => [
            ['duration' => 3333, 'filter' => 'vivid', 'transition' => 'zoomIn', 'media' => 'assets/demo/urban_skate.mp4'],
            ['duration' => 3333, 'filter' => 'punchy', 'transition' => 'slideLeft', 'media' => 'assets/demo/tokyo_shinjuku.mp4'],
            ['duration' => 3334, 'filter' => 'cleanPop', 'transition' => 'fade', 'media' => 'assets/demo/ramen_bar.mp4'],
        ],
        'texts' => [
            ['text' => 'WAIT FOR IT 🚀', 'font' => 'Inter', 'size' => 30, 'color' => 0xFFFFFFFF, 'bg' => 0xFF00C9FF, 'start' => 0, 'end' => 5000, 'anim' => 'scale', 'x' => 0.5, 'y' => 0.2],
            ['text' => 'Did you catch that? 👀', 'font' => 'SpaceMono', 'size' => 20, 'color' => 0xFFE0F2F1, 'bg' => null, 'start' => 5000, 'end' => 10000, 'anim' => 'slideUp', 'x' => 0.5, 'y' => 0.85],
        ]
    ]
];

// Helper to build project JSON matching ProjectModel.fromJson structure
function buildProjectJson($tmpl) {
    $clips = [];
    $offset = 0;
    $i = 1;
    foreach ($tmpl['slots'] as $s) {
        $dur = $s['duration'];
        $clips[] = [
            'id' => 'clip_' . $tmpl['id'] . '_' . $i,
            'mediaPath' => $s['media'],
            'name' => 'Slot #' . $i . ' (' . basename($s['media'], '.' . pathinfo($s['media'], PATHINFO_EXTENSION)) . ')',
            'sourceDurationMs' => $dur,
            'timelineStartMs' => $offset,
            'timelineEndMs' => $offset + $dur,
            'trimStartMs' => 0,
            'trimEndMs' => $dur,
            'speed' => 1.0,
            'volume' => 1.0,
            'isMuted' => false,
            'filterType' => $s['filter'],
            'filterIntensity' => 1.0,
            'effectType' => 'none',
            'effectIntensity' => 0.0,
            'brightness' => 0.0,
            'contrast' => 1.0,
            'saturation' => 1.0,
            'transitionIn' => $s['transition'],
            'transitionDurationMs' => 500,
            'rotationDegrees' => 0.0,
            'isFlippedHorizontally' => false,
            'isFlippedVertically' => false,
            'opacity' => 1.0,
            'zoomScale' => 1.0,
            'positionX' => 0.0,
            'positionY' => 0.0,
            'blurSigma' => 0.0,
            'fadeInDurationMs' => 0,
            'fadeOutDurationMs' => 0,
            'animationIn' => 'none',
            'animationInDurationMs' => 500,
            'animationOut' => 'none',
            'animationOutDurationMs' => 500,
            'animationCombo' => 'none',
            'speedCurve' => 'none',
            'isReversed' => false,
            'isOverlay' => false,
            'crop' => null,
            'mask' => null,
            'chromaKey' => null,
            'keyframes' => []
        ];
        $offset += $dur;
        $i++;
    }

    $audioClips = [
        [
            'id' => 'audio_' . $tmpl['id'],
            'mediaPath' => $tmpl['audio_url'],
            'title' => $tmpl['audio_title'],
            'category' => 'music',
            'timelineStartMs' => 0,
            'timelineEndMs' => $tmpl['duration_ms'],
            'trimStartMs' => 0,
            'trimEndMs' => $tmpl['duration_ms'],
            'volume' => 1.0,
            'isMuted' => false,
            'fadeInMs' => 300,
            'fadeOutMs' => 500,
            'waveformSamples' => [0.2, 0.5, 0.8, 0.6, 0.9, 0.7, 0.4, 0.8, 0.9, 0.5]
        ]
    ];

    $textOverlays = [];
    $tIdx = 1;
    foreach ($tmpl['texts'] as $t) {
        $textOverlays[] = [
            'id' => 'text_' . $tmpl['id'] . '_' . $tIdx,
            'text' => $t['text'],
            'fontFamily' => $t['font'],
            'fontSize' => $t['size'],
            'colorHex' => $t['color'],
            'backgroundColorHex' => $t['bg'],
            'outlineColorHex' => null,
            'outlineWidth' => 0.0,
            'posX' => $t['x'],
            'posY' => $t['y'],
            'scale' => 1.0,
            'rotation' => 0.0,
            'timelineStartMs' => $t['start'],
            'timelineEndMs' => $t['end'],
            'animationType' => $t['anim']
        ];
        $tIdx++;
    }

    return json_encode([
        'id' => $tmpl['id'],
        'title' => $tmpl['title'],
        'aspectRatio' => $tmpl['aspect_ratio'],
        'fps' => 30,
        'resolutionWidth' => ($tmpl['aspect_ratio'] === 'ratio16_9') ? 1920 : 1080,
        'resolutionHeight' => ($tmpl['aspect_ratio'] === 'ratio16_9') ? 1080 : 1920,
        'durationMs' => $tmpl['duration_ms'],
        'syncStatus' => 'synced',
        'lastPlayheadPositionMs' => 0,
        'videoClips' => $clips,
        'audioClips' => $audioClips,
        'textOverlays' => $textOverlays,
        'stickerOverlays' => [],
        'subtitles' => [],
        'effectClips' => [],
        'animationClips' => []
    ], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
}

// Prepare statement to insert or update
$sql = "INSERT INTO templates (
    id, title, category, badge, description, prompt, author, aspect_ratio,
    duration_ms, clips_count, downloads_count, preview_gradient_start,
    preview_gradient_end, preview_video_url, preview_image_url, audio_title,
    audio_url, project_json, tags, is_pro, is_trending, is_new, is_popular,
    is_enabled, display_order, created_at, updated_at
) VALUES (
    :id, :title, :category, :badge, :description, :prompt, :author, :aspect_ratio,
    :duration_ms, :clips_count, :downloads_count, :preview_gradient_start,
    :preview_gradient_end, :preview_video_url, :preview_image_url, :audio_title,
    :audio_url, :project_json, :tags, :is_pro, :is_trending, :is_new, :is_popular,
    1, :display_order, NOW(), NOW()
) ON DUPLICATE KEY UPDATE
    title = VALUES(title),
    category = VALUES(category),
    badge = VALUES(badge),
    description = VALUES(description),
    prompt = VALUES(prompt),
    author = VALUES(author),
    aspect_ratio = VALUES(aspect_ratio),
    duration_ms = VALUES(duration_ms),
    clips_count = VALUES(clips_count),
    downloads_count = VALUES(downloads_count),
    preview_gradient_start = VALUES(preview_gradient_start),
    preview_gradient_end = VALUES(preview_gradient_end),
    preview_video_url = VALUES(preview_video_url),
    preview_image_url = VALUES(preview_image_url),
    audio_title = VALUES(audio_title),
    audio_url = VALUES(audio_url),
    project_json = VALUES(project_json),
    tags = VALUES(tags),
    is_pro = VALUES(is_pro),
    is_trending = VALUES(is_trending),
    is_new = VALUES(is_new),
    is_popular = VALUES(is_popular),
    is_enabled = 1,
    display_order = VALUES(display_order),
    updated_at = NOW()";

$stmt = $pdo->prepare($sql);

$seededCount = 0;
foreach ($templates as $t) {
    $projJson = buildProjectJson($t);
    $stmt->execute([
        ':id' => $t['id'],
        ':title' => $t['title'],
        ':category' => $t['category'],
        ':badge' => $t['badge'],
        ':description' => $t['description'],
        ':prompt' => $t['prompt'],
        ':author' => $t['author'],
        ':aspect_ratio' => $t['aspect_ratio'],
        ':duration_ms' => $t['duration_ms'],
        ':clips_count' => $t['clips_count'],
        ':downloads_count' => $t['downloads_count'],
        ':preview_gradient_start' => $t['preview_gradient_start'],
        ':preview_gradient_end' => $t['preview_gradient_end'],
        ':preview_video_url' => $t['preview_video_url'],
        ':preview_image_url' => $t['preview_image_url'],
        ':audio_title' => $t['audio_title'],
        ':audio_url' => $t['audio_url'],
        ':project_json' => $projJson,
        ':tags' => $t['tags'],
        ':is_pro' => $t['is_pro'],
        ':is_trending' => $t['is_trending'],
        ':is_new' => $t['is_new'],
        ':is_popular' => $t['is_popular'],
        ':display_order' => $t['display_order'],
    ]);
    $seededCount++;
    echo "✓ [{$t['display_order']}/25] Seeded template: {$t['title']} ({$t['category']})\n";
}

echo "\nSuccessfully seeded $seededCount templates into database!\n";
