import 'package:flutter/material.dart';

enum VideoEffectCategory {
  trending('Trending'),
  classic('Classic'),
  newHits('NEW'),
  hits('Hits'),
  introOutro('Intro & Outro'),
  bodyEffects('Body Effects'),
  glitch('Glitch'),
  retro('Retro'),
  lightEffect('Light Effect'),
  atmosphere('Atmosphere'),
  blur('Blur'),
  party('Party'),
  distortion('Distortion'),
  all('All');

  final String label;
  const VideoEffectCategory(this.label);
}

enum VideoEffectType {
  none(
    label: 'None',
    category: VideoEffectCategory.trending,
    description: 'No effect applied',
    icon: Icons.block,
    color1: Color(0xFF2C2F38),
    color2: Color(0xFF1E2028),
  ),
  explosion(
    label: 'Explosion',
    category: VideoEffectCategory.trending,
    description: 'Fiery gold shockwave particle blast',
    icon: Icons.local_fire_department,
    color1: Color(0xFFFF9900),
    color2: Color(0xFFFF3300),
  ),
  videoCam(
    label: 'Video Cam',
    category: VideoEffectCategory.trending,
    description: 'Vintage camcorder viewfinder with REC, crosshairs & timestamp',
    icon: Icons.videocam_outlined,
    color1: Color(0xFF4A90E2),
    color2: Color(0xFF1B2A47),
  ),
  rollingFilm(
    label: 'Rolling Film',
    category: VideoEffectCategory.trending,
    description: 'Vintage 35mm film sprockets with rolling scanlines',
    icon: Icons.movie_filter,
    color1: Color(0xFF434343),
    color2: Color(0xFF000000),
  ),
  phoneDrift(
    label: 'Phone Drift',
    category: VideoEffectCategory.trending,
    description: 'Smooth floating handheld camera drift, inertia swing & tilt',
    icon: Icons.screen_rotation,
    color1: Color(0xFF5C258D),
    color2: Color(0xFF4389A2),
  ),
  lightningCloud(
    label: 'Lightning C..',
    category: VideoEffectCategory.trending,
    description: 'Thunderstorm dark clouds with intense electric branching lightning bolts',
    icon: Icons.thunderstorm_outlined,
    color1: Color(0xFF1A2980),
    color2: Color(0xFF26D0CE),
  ),
  crossSplit(
    label: 'Cross Split',
    category: VideoEffectCategory.trending,
    description: '4-panel cross split screen with quad mirrors and dynamic panels',
    icon: Icons.grid_view_rounded,
    color1: Color(0xFF11998E),
    color2: Color(0xFF38EF7D),
  ),
  superLarge(
    label: 'Super-large..',
    category: VideoEffectCategory.trending,
    description: 'Cinematic breathing zoom with colorful bokeh light discs',
    icon: Icons.zoom_out_map,
    color1: Color(0xFF00C6FF),
    color2: Color(0xFF0072FF),
  ),
  obliqueBlur(
    label: 'Oblique Blur',
    category: VideoEffectCategory.trending,
    description: '45-degree diagonal action prism blur with chromatic aberration',
    icon: Icons.blur_linear_outlined,
    color1: Color(0xFFFF0844),
    color2: Color(0xFFFFB199),
  ),
  edgeSilhouette(
    label: 'Edge Silhouette',
    category: VideoEffectCategory.trending,
    description: 'Luminous neon contour detection tracing the subject with glowing aura',
    icon: Icons.person_pin_circle_outlined,
    color1: Color(0xFFFF007A),
    color2: Color(0xFF7B2CBF),
  ),
  citySunset(
    label: 'City Sunset',
    category: VideoEffectCategory.trending,
    description: 'Golden hour warm skyline haze with atmospheric sun flare and bloom',
    icon: Icons.wb_twilight_outlined,
    color1: Color(0xFFFF8008),
    color2: Color(0xFFFFC837),
  ),
  verticalFilm(
    label: 'Vertical Film',
    category: VideoEffectCategory.classic,
    description: 'Continuous vertical rolling 8mm/16mm film reel with sprocket margins',
    icon: Icons.video_library_outlined,
    color1: Color(0xFF3A3D40),
    color2: Color(0xFF181719),
  ),
  prismRainbow(
    label: 'Prism Flare',
    category: VideoEffectCategory.newHits,
    description: 'Prismatic rainbow crystal light refraction and holographic glints',
    icon: Icons.looks_outlined,
    color1: Color(0xFFFF0080),
    color2: Color(0xFF7928CA),
  ),
  flash(
    label: 'Flash',
    category: VideoEffectCategory.trending,
    description: 'High-speed luminous white strobe pulse',
    icon: Icons.flash_on,
    color1: Color(0xFFFF007A),
    color2: Color(0xFFFF5E36),
  ),
  blackFlash2(
    label: 'Black Flash 2',
    category: VideoEffectCategory.trending,
    description: 'Rhythmic dark strobe pulse beat',
    icon: Icons.dark_mode,
    color1: Color(0xFF8E2DE2),
    color2: Color(0xFF4A00E0),
  ),
  fadeIn(
    label: 'Fade In',
    category: VideoEffectCategory.introOutro,
    description: 'Cinematic soft luminance fade entrance',
    icon: Icons.gradient,
    color1: Color(0xFFF7971E),
    color2: Color(0xFFFFD200),
  ),
  shake(
    label: 'Shake',
    category: VideoEffectCategory.trending,
    description: 'Vibrant dynamic camera jitter shake',
    icon: Icons.vibration,
    color1: Color(0xFFE52D27),
    color2: Color(0xFFB31217),
  ),
  glitch(
    label: 'RGB Glitch',
    category: VideoEffectCategory.glitch,
    description: 'Chromatic aberration slice and digital glitch',
    icon: Icons.broken_image,
    color1: Color(0xFF00F2FE),
    color2: Color(0xFF4FACFE),
  ),
  neonGlow(
    label: 'Neon Glow',
    category: VideoEffectCategory.lightEffect,
    description: 'Cyberpunk edge luminescent neon shine',
    icon: Icons.auto_awesome,
    color1: Color(0xFFB92B27),
    color2: Color(0xFF1565C0),
  ),
  retroVhs(
    label: 'Retro VHS',
    category: VideoEffectCategory.retro,
    description: '90s CRT scanlines with VHS tracking distortion',
    icon: Icons.videocam,
    color1: Color(0xFF654EA3),
    color2: Color(0xFFEAAFC8),
  ),
  sparkles(
    label: 'Sparkles',
    category: VideoEffectCategory.hits,
    description: 'Glittering starlight sparkle particles',
    icon: Icons.star_half,
    color1: Color(0xFFFDC830),
    color2: Color(0xFFF37335),
  ),
  heartFloat(
    label: 'Heart Float',
    category: VideoEffectCategory.hits,
    description: 'Romantic rising heart particles',
    icon: Icons.favorite,
    color1: Color(0xFFFF416C),
    color2: Color(0xFFFF4B2B),
  ),
  kaleidoscope(
    label: 'Prism Mirror',
    category: VideoEffectCategory.distortion,
    description: 'Multi-angle kaleidoscope mirror reflection',
    icon: Icons.blur_linear,
    color1: Color(0xFF3A1C71),
    color2: Color(0xFFD76D77),
  ),
  heartbeatZoom(
    label: 'Beat Pulse',
    category: VideoEffectCategory.bodyEffects,
    description: 'Rhythmic bass-drop camera heartbeat zoom',
    icon: Icons.hearing,
    color1: Color(0xFF11998E),
    color2: Color(0xFF38EF7D),
  ),
  edgeGlow(
    label: 'Edge Glow',
    category: VideoEffectCategory.lightEffect,
    description: 'Vibrant neon silhouette edge luminescence',
    icon: Icons.highlight,
    color1: Color(0xFF00F5D4),
    color2: Color(0xFF7B2CBF),
  ),
  filmGrain(
    label: 'Film Grain',
    category: VideoEffectCategory.retro,
    description: 'Vintage 8mm film dust, scratches and cinema grain',
    icon: Icons.grain,
    color1: Color(0xFF3A3D40),
    color2: Color(0xFF181719),
  ),
  lightLeak(
    label: 'Light Leak',
    category: VideoEffectCategory.lightEffect,
    description: 'Warm golden sunset anamorphic lens flare',
    icon: Icons.wb_sunny,
    color1: Color(0xFFFF8008),
    color2: Color(0xFFFFC837),
  ),
  laserBeams(
    label: 'Laser Beams',
    category: VideoEffectCategory.party,
    description: 'High-energy futuristic neon laser sweeps',
    icon: Icons.bolt,
    color1: Color(0xFFFF0055),
    color2: Color(0xFF00F0FF),
  ),
  radialBlur(
    label: 'Radial Blur',
    category: VideoEffectCategory.blur,
    description: 'High-speed action zoom burst radial blur',
    icon: Icons.blur_circular,
    color1: Color(0xFF4A00E0),
    color2: Color(0xFF8E2DE2),
  ),
  motionBlur(
    label: 'Motion Blur',
    category: VideoEffectCategory.blur,
    description: 'Directional high-velocity cinematic motion streak',
    icon: Icons.blur_linear,
    color1: Color(0xFF1F4037),
    color2: Color(0xFF99F2C8),
  ),
  softDream(
    label: 'Soft Dream',
    category: VideoEffectCategory.atmosphere,
    description: 'Ethereal gaussian pastel dreamy glow',
    icon: Icons.cloud_outlined,
    color1: Color(0xFFFBC2EB),
    color2: Color(0xFFA6C1EE),
  ),
  waveWarp(
    label: 'Wave Warp',
    category: VideoEffectCategory.distortion,
    description: 'Liquid ocean ripple wave distortion',
    icon: Icons.waves,
    color1: Color(0xFF4E65FF),
    color2: Color(0xFF92EFFD),
  ),
  pixelate(
    label: '8-Bit Pixel',
    category: VideoEffectCategory.glitch,
    description: 'Retro arcade 8-bit mosaic pixelation shift',
    icon: Icons.grid_view,
    color1: Color(0xFFFC5C7D),
    color2: Color(0xFF6A82FB),
  ),
  vcrDistort(
    label: 'VCR Distort',
    category: VideoEffectCategory.glitch,
    description: 'Analog magnetic tape tracking static band',
    icon: Icons.speaker,
    color1: Color(0xFF302B63),
    color2: Color(0xFF24243E),
  ),
  rgbSplit(
    label: 'RGB Split',
    category: VideoEffectCategory.newHits,
    description: 'Dual red & cyan stereo chromatic shift',
    icon: Icons.splitscreen,
    color1: Color(0xFFFF0844),
    color2: Color(0xFFFFB199),
  ),
  mirrorQuad(
    label: 'Mirror Quad',
    category: VideoEffectCategory.distortion,
    description: '4-quadrant symmetric kaleidoscope mirror',
    icon: Icons.grid_4x4,
    color1: Color(0xFF134E5E),
    color2: Color(0xFF71B280),
  ),
  discoStrobe(
    label: 'Disco Strobe',
    category: VideoEffectCategory.party,
    description: 'Multicolor dancefloor club strobe pulse',
    icon: Icons.celebration,
    color1: Color(0xFFFF007F),
    color2: Color(0xFF00FFFF),
  ),
  bassRumble(
    label: 'Bass Rumble',
    category: VideoEffectCategory.party,
    description: 'Low-frequency subwoofer screen vibration',
    icon: Icons.graphic_eq,
    color1: Color(0xFFF857A6),
    color2: Color(0xFFFF5858),
  ),
  starGlow(
    label: 'Star Glow',
    category: VideoEffectCategory.lightEffect,
    description: 'Heavenly 4-point starlight glint bloom',
    icon: Icons.stars,
    color1: Color(0xFFF7797D),
    color2: Color(0xFFFBD786),
  ),
  sepiaVintage(
    label: 'Sepia 1920',
    category: VideoEffectCategory.classic,
    description: 'Silent cinema antique warm sepia vignette',
    icon: Icons.photo_filter,
    color1: Color(0xFFB79891),
    color2: Color(0xFF94716B),
  ),
  cinemaScope(
    label: 'Cinemascope',
    category: VideoEffectCategory.classic,
    description: '2.39:1 anamorphic cinema widescreen bars with slow push',
    icon: Icons.crop_16_9,
    color1: Color(0xFF232526),
    color2: Color(0xFF414345),
  ),
  matrixRain(
    label: 'Matrix Code',
    category: VideoEffectCategory.glitch,
    description: 'Digital green rain matrix falling characters',
    icon: Icons.code,
    color1: Color(0xFF00FF87),
    color2: Color(0xFF60EFFF),
  ),
  cyberGrid(
    label: 'Cyber Grid',
    category: VideoEffectCategory.retro,
    description: 'Synthwave retro 80s 3D perspective horizon grid',
    icon: Icons.view_in_ar,
    color1: Color(0xFFFF007F),
    color2: Color(0xFF7B2CBF),
  ),
  fireEmbers(
    label: 'Fire Embers',
    category: VideoEffectCategory.atmosphere,
    description: 'Rising glowing campfire embers and hot spark particles',
    icon: Icons.whatshot,
    color1: Color(0xFFFF4E50),
    color2: Color(0xFFF9D423),
  ),
  snowFall(
    label: 'Snow Fall',
    category: VideoEffectCategory.atmosphere,
    description: 'Gentle drifting winter snowflakes and frosty aura',
    icon: Icons.ac_unit,
    color1: Color(0xFFE0EAFC),
    color2: Color(0xFFCFDEF3),
  ),
  rainStorm(
    label: 'Rain Storm',
    category: VideoEffectCategory.atmosphere,
    description: 'Cinematic torrential rain with water droplet streaks',
    icon: Icons.water_drop,
    color1: Color(0xFF3A6073),
    color2: Color(0xFF16222F),
  ),
  lightningBolt(
    label: 'Lightning',
    category: VideoEffectCategory.lightEffect,
    description: 'High-voltage electric thunderstorm flash strike',
    icon: Icons.flash_auto,
    color1: Color(0xFF00E5FF),
    color2: Color(0xFF2979FF),
  ),
  goldenDust(
    label: 'Golden Dust',
    category: VideoEffectCategory.lightEffect,
    description: 'Luxury floating golden bokeh light particles',
    icon: Icons.flare,
    color1: Color(0xFFFFD700),
    color2: Color(0xFFFFA500),
  ),
  smokeAtmosphere(
    label: 'Stage Smoke',
    category: VideoEffectCategory.atmosphere,
    description: 'Drifting theatrical stage fog and volumetric smoke',
    icon: Icons.cloud,
    color1: Color(0xFF536976),
    color2: Color(0xFF292E49),
  ),
  bubbleFloat(
    label: 'Soap Bubbles',
    category: VideoEffectCategory.party,
    description: 'Iridescent colorful floating soap bubbles',
    icon: Icons.bubble_chart,
    color1: Color(0xFF89F7FE),
    color2: Color(0xFF66A6FF),
  ),
  fireworks(
    label: 'Fireworks',
    category: VideoEffectCategory.party,
    description: 'Vibrant celebratory night sky fireworks blast',
    icon: Icons.celebration_outlined,
    color1: Color(0xFFFF0844),
    color2: Color(0xFFFFB199),
  ),
  lensZoomBlur(
    label: 'Snap Zoom',
    category: VideoEffectCategory.blur,
    description: 'Action cinema fast directional snap-zoom burst',
    icon: Icons.center_focus_strong,
    color1: Color(0xFF654EA3),
    color2: Color(0xFFEAAFC8),
  ),
  diamondSparkle(
    label: 'Diamond Shimmer',
    category: VideoEffectCategory.newHits,
    description: 'Hyper-bright luxury gemstone star sparkle glints',
    icon: Icons.diamond_outlined,
    color1: Color(0xFF00F2FE),
    color2: Color(0xFF4FACFE),
  ),
  hologramGlitch(
    label: 'Hologram',
    category: VideoEffectCategory.newHits,
    description: 'Sci-fi cyan scanline holographic transmission flicker',
    icon: Icons.perm_scan_wifi,
    color1: Color(0xFF00C6FF),
    color2: Color(0xFF0072FF),
  ),
  vignetteDark(
    label: 'Cinema Vignette',
    category: VideoEffectCategory.classic,
    description: 'Dramatic dark edge vignette corner shading',
    icon: Icons.vignette,
    color1: Color(0xFF2C3E50),
    color2: Color(0xFF000000),
  ),
  thermalVision(
    label: 'Thermal Heat',
    category: VideoEffectCategory.distortion,
    description: 'Infrared predator thermal heat sensor map',
    icon: Icons.thermostat,
    color1: Color(0xFFFF0000),
    color2: Color(0xFF0000FF),
  ),
  nightVision(
    label: 'Night Vision',
    category: VideoEffectCategory.classic,
    description: 'Military green phosphorescent sensor grain with halo',
    icon: Icons.visibility,
    color1: Color(0xFF00FF00),
    color2: Color(0xFF003300),
  ),
  halftoneComic(
    label: 'Pop Comic',
    category: VideoEffectCategory.retro,
    description: 'Vintage Pop-art comic book dot screen pattern',
    icon: Icons.lens,
    color1: Color(0xFFFFEE7D),
    color2: Color(0xFFFF5252),
  ),
  colorInvert(
    label: 'Invert Solar',
    category: VideoEffectCategory.distortion,
    description: 'Negative inverted photographic film solarization',
    icon: Icons.invert_colors,
    color1: Color(0xFF333399),
    color2: Color(0xFFFF00CC),
  ),
  duotoneNeon(
    label: 'Duotone Neon',
    category: VideoEffectCategory.trending,
    description: 'Stylized two-tone cyberpunk violet & teal gradient map',
    icon: Icons.style,
    color1: Color(0xFFFA709A),
    color2: Color(0xFFFEE140),
  ),
  oldTvStatic(
    label: 'TV Static',
    category: VideoEffectCategory.retro,
    description: 'Analog black & white broadcast television snow static',
    icon: Icons.tv_off,
    color1: Color(0xFF8E9EAB),
    color2: Color(0xFFEEF2F3),
  ),
  dizzySpin(
    label: 'Dizzy Vortex',
    category: VideoEffectCategory.distortion,
    description: 'Hypnotic swirling spiral vertigo distortion',
    icon: Icons.cyclone,
    color1: Color(0xFF8A2387),
    color2: Color(0xFFE94057),
  ),
  ghostTrail(
    label: 'Ghost Echo',
    category: VideoEffectCategory.bodyEffects,
    description: 'Dreamy slow-motion multi-exposure motion ghost trail',
    icon: Icons.motion_photos_on,
    color1: Color(0xFF7028E4),
    color2: Color(0xFFE5B2CA),
  ),
  butterflySwarm(
    label: 'Butterflies',
    category: VideoEffectCategory.hits,
    description: 'Magical fluttering starlight neon butterflies',
    icon: Icons.cruelty_free,
    color1: Color(0xFFFF758C),
    color2: Color(0xFFFF7EB3),
  ),
  speedLines(
    label: 'Speed Lines',
    category: VideoEffectCategory.trending,
    description: 'Anime manga velocity action burst lines',
    icon: Icons.double_arrow,
    color1: Color(0xFFF857A6),
    color2: Color(0xFFFF5858),
  ),
  glowRings(
    label: 'Energy Halo',
    category: VideoEffectCategory.bodyEffects,
    description: 'Pulsing circular energy aura rings around subject',
    icon: Icons.radio_button_checked,
    color1: Color(0xFF00F5D4),
    color2: Color(0xFF00BBF9),
  ),
  colorPulse(
    label: 'Color Pulse',
    category: VideoEffectCategory.party,
    description: 'Rhythmic dynamic RGB color cycling saturation wave',
    icon: Icons.palette,
    color1: Color(0xFFFF0080),
    color2: Color(0xFF7928CA),
  ),
  confettiParty(
    label: 'Confetti',
    category: VideoEffectCategory.party,
    description: 'Festive multicolored celebratory falling confetti',
    icon: Icons.celebration,
    color1: Color(0xFFFF007F),
    color2: Color(0xFFFFD700),
  ),
  filmBurn(
    label: 'Film Burn',
    category: VideoEffectCategory.retro,
    description: 'Vintage 35mm golden film burn edge flare transition',
    icon: Icons.local_fire_department_outlined,
    color1: Color(0xFFFF8008),
    color2: Color(0xFFFF3300),
  ),
  waterRipples(
    label: 'Water Ripple',
    category: VideoEffectCategory.distortion,
    description: 'Refractive clear liquid water drop surface wave',
    icon: Icons.water,
    color1: Color(0xFF4FACFE),
    color2: Color(0xFF00F2FE),
  ),
  iceFrost(
    label: 'Ice Frost',
    category: VideoEffectCategory.atmosphere,
    description: 'Freezing winter ice crystal frosty borders',
    icon: Icons.severe_cold,
    color1: Color(0xFFE0EAFC),
    color2: Color(0xFF66A6FF),
  ),
  heartGlow(
    label: 'Heart Glow',
    category: VideoEffectCategory.bodyEffects,
    description: 'Pulsing glowing neon heart silhouette border',
    icon: Icons.favorite_border,
    color1: Color(0xFFFF007A),
    color2: Color(0xFFFF5E36),
  ),
  fireAura(
    label: 'Fire Aura',
    category: VideoEffectCategory.bodyEffects,
    description: 'Blazing fiery burning dragon silhouette outline',
    icon: Icons.local_fire_department,
    color1: Color(0xFFFF4E50),
    color2: Color(0xFFF9D423),
  ),
  comicBoom(
    label: 'Comic Boom',
    category: VideoEffectCategory.newHits,
    description: 'Halftone Pop-Art action comic explosion burst',
    icon: Icons.auto_awesome_motion,
    color1: Color(0xFFFFEE7D),
    color2: Color(0xFFFF0844),
  ),
  vhsPause(
    label: 'VHS Pause',
    category: VideoEffectCategory.retro,
    description: '90s tape pause magnetic tracking jitter glitch',
    icon: Icons.pause_circle_outline,
    color1: Color(0xFF302B63),
    color2: Color(0xFF24243E),
  ),
  mirrorTunnel(
    label: 'Mirror Tunnel',
    category: VideoEffectCategory.distortion,
    description: 'Infinite psychedelic concentric reflection tunnel',
    icon: Icons.all_inclusive,
    color1: Color(0xFF8E2DE2),
    color2: Color(0xFF4A00E0),
  ),
  bloomGlow(
    label: 'Bloom Glow',
    category: VideoEffectCategory.lightEffect,
    description: 'Dreamy hyper-luminous soft focus HDR bloom',
    icon: Icons.brightness_high,
    color1: Color(0xFFFA709A),
    color2: Color(0xFFFEE140),
  ),
  polaroidFrame(
    label: 'Polaroid',
    category: VideoEffectCategory.classic,
    description: 'Instant vintage camera border with nostalgic warmth',
    icon: Icons.camera_enhance_outlined,
    color1: Color(0xFFD4D3DD),
    color2: Color(0xFFEFEFBB),
  ),
  cyberScan(
    label: 'Cyber Scan',
    category: VideoEffectCategory.newHits,
    description: 'Futuristic blue biometric HUD laser target scanner',
    icon: Icons.document_scanner,
    color1: Color(0xFF00F5D4),
    color2: Color(0xFF7B2CBF),
  );

  final String label;
  final VideoEffectCategory category;
  final String description;
  final IconData icon;
  final Color color1;
  final Color color2;

  const VideoEffectType({
    required this.label,
    required this.category,
    required this.description,
    required this.icon,
    required this.color1,
    required this.color2,
  });

  static VideoEffectType fromString(String? val) {
    return VideoEffectType.values.firstWhere(
      (e) => e.name == val,
      orElse: () => VideoEffectType.none,
    );
  }
}
