<?php
/**
 * ProCut – AI Presets Pure-PHP Seed Function
 * Safe to include from any PHP page. No HTML output.
 * Returns ['inserted'=>N, 'updated'=>N, 'total'=>N]
 */

function seedAiPresets(): array {
    $inserted = 0;
    $updated  = 0;

    // Ensure table exists
    try {
        Database::query("
            CREATE TABLE IF NOT EXISTS ai_presets (
                id VARCHAR(64) PRIMARY KEY,
                type ENUM('photo','video') NOT NULL DEFAULT 'photo',
                title VARCHAR(255) NOT NULL,
                category VARCHAR(100) NOT NULL DEFAULT 'Trending',
                prompt TEXT NOT NULL,
                negative_prompt TEXT NULL,
                reference_image_url VARCHAR(500) NULL,
                preview_video_url VARCHAR(500) NULL,
                model_name VARCHAR(100) NULL,
                style VARCHAR(100) NULL,
                camera_movement VARCHAR(100) NULL,
                lighting VARCHAR(100) NULL,
                seed VARCHAR(64) NULL,
                duration_text VARCHAR(50) NULL,
                tags VARCHAR(500) NULL,
                is_active TINYINT(1) DEFAULT 1,
                display_order INT DEFAULT 0,
                created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
                updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                INDEX idx_ai_type (type),
                INDEX idx_ai_order (display_order)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
        ");
    } catch (Throwable $e) { /* already exists */ }

    $presets = [
        // ── 80s & Retro ──
        ['id'=>'photo_80s_synthwave','type'=>'photo','title'=>'80s Synthwave Retro','category'=>'80s','prompt'=>'Authentic 1980s retro synthwave portrait of a stylish protagonist wearing classic mirrored aviator sunglasses and a distressed black leather bomber jacket with neon pink interior lining. Background features a luminous neon grid horizon fading into a giant retro sun. Volumetric magenta, hot cyan, and violet rim lighting. VHS tape tracking distortion, analog 35mm film grain, Kodachrome 64 color science, ultra-detailed 8K photorealism.','negative_prompt'=>'blurry, modern digital look, low resolution, bad anatomy, watermark','reference_image_url'=>'assets/demo/ai_80s_synthwave.jpg','preview_video_url'=>null,'model_name'=>'Flux.1 Pro','style'=>'80s AI Art','camera_movement'=>'50mm f/1.4 Analog Prime','lighting'=>'Neon Laser Grid & Cyan Rim Light','seed'=>'1083721','duration_text'=>'Static','tags'=>'1980s, Synthwave, Neon Grid, VHS Analog, Aviators','is_active'=>1,'display_order'=>1],
        ['id'=>'photo_80s_polaroid','type'=>'photo','title'=>'80s Flash Polaroid','category'=>'80s','prompt'=>'Nostalgic 1985 flash snapshot polaroid photo captured in a retro discotheque. Direct on-camera xenon flash, authentic vintage warm golden color grading with faded cyan shadows, tactile chemical paper texture, slight light leak, organic Kodak 400 film grain, 8K instant photography aesthetic.','negative_prompt'=>'modern digital crispness, HDR, 3D render, oversharpened, plastic skin','reference_image_url'=>'assets/demo/tmpl-retro-90s.jpg','preview_video_url'=>null,'model_name'=>'Midjourney v6.1','style'=>'80s AI Art','camera_movement'=>'Polaroid 600 Lens (f/11)','lighting'=>'Harsh Direct On-Camera Flash','seed'=>'1167442','duration_text'=>'Static','tags'=>'Polaroid, Direct Flash, Light Leak, 80s Party','is_active'=>1,'display_order'=>2],
        ['id'=>'photo_80s_pastel_vaporwave','type'=>'photo','title'=>'Pastel Horizon Vaporwave','category'=>'80s','prompt'=>'Dreamy aesthetic 90s vaporwave synthpop artistic portrait, subject draped in soft pastel oversized streetwear gazing into the distance. Surreal sunset sky blending cotton-candy pink and mint green gradients with floating neon palm tree silhouettes. Lo-Fi VHS scanlines, Fuji Pro 400H color palette, 8K ultra-detailed photorealistic portrait.','negative_prompt'=>'harsh dark shadows, high contrast monochrome, realistic modern city','reference_image_url'=>'assets/demo/ai_vaporwave_sunset.jpg','preview_video_url'=>null,'model_name'=>'SDXL Turbo','style'=>'80s AI Art','camera_movement'=>'35mm Film Lens with Star Filter','lighting'=>'Pastel Ambient Gradient & Holographic Glint','seed'=>'1251163','duration_text'=>'Static','tags'=>'Vaporwave, Pastel Gradient, Marble Bust, Neon Palms, Lo-Fi','is_active'=>1,'display_order'=>3],
        ['id'=>'photo_80s_miami_sunset','type'=>'photo','title'=>'80s Miami Vice Palms','category'=>'80s','prompt'=>'Cinematic 1984 Miami Vice golden hour portrait. Dramatic low-angle tropical sunset with glowing fiery orange and magenta hues illuminating royal palm tree silhouettes. Art deco hotel neon signs shimmering on a vintage Ferrari Testarossa. Shot on 85mm f/1.4 Cine lens with anamorphic flares and warm 35mm film warmth.','negative_prompt'=>'modern skyscrapers, cold blue tones, digital rendering, flat lighting','reference_image_url'=>'assets/demo/ai_vaporwave_sunset.jpg','preview_video_url'=>null,'model_name'=>'Flux.1 Schnell','style'=>'80s AI Art','camera_movement'=>'85mm f/1.8 Portrait Telephoto','lighting'=>'Hot Tropical Golden Hour & Hot Pink Fill','seed'=>'1334884','duration_text'=>'Static','tags'=>'Miami Vice, Pastel Suit, Ocean Boulevard, Art Deco','is_active'=>1,'display_order'=>4],
        ['id'=>'photo_80s_arcade_neon','type'=>'photo','title'=>'80s Cyber Arcade Gamer','category'=>'80s','prompt'=>'Atmospheric 1980s neon arcade portrait, subject sitting in front of classic glowing CRT arcade cabinets displaying pixelated space shooter games. Vivid cyan and hot magenta cathode-ray tube phosphor glow. Acid-wash denim jacket with enamel retro badges, soft atmospheric haze and dust motes in beams of colored arcade light, 8K cinematic Kodacolor aesthetic.','negative_prompt'=>'modern flat screens, modern clothing, sterile room, low quality','reference_image_url'=>'assets/demo/ai_cyberpunk_neon.jpg','preview_video_url'=>null,'model_name'=>'Midjourney v6.1','style'=>'80s AI Art','camera_movement'=>'50mm f/1.2 Low Light Lens','lighting'=>'Multi-color CRT Phosphor Glow','seed'=>'1418605','duration_text'=>'Static','tags'=>'Arcade, CRT Monitor, 80s Gamer, Neon Glow, Pixel Art','is_active'=>1,'display_order'=>5],

        // ── Trending ──
        ['id'=>'photo_trending_cyberpunk','type'=>'photo','title'=>'Tokyo Cyberpunk Rain','category'=>'Trending','prompt'=>'Masterpiece 8K photorealistic editorial portrait of a charismatic cyberpunk protagonist standing in the pouring rain of Neo-Tokyo Shinjuku alleyways at 2:00 AM. Transparent umbrella catching prismatic raindrops and reflecting neon billboards. Distressed oversized matte-black technical bomber jacket with luminous cyan fiber-optic seams. Wet asphalt streets reflecting brilliant electric magenta, ultraviolet, and turquoise signage. Dense volumetric steam, shot on Hasselblad H6D-100c with 85mm f/1.2 Cine Prime lens, cinematic teal and orange color grading.','negative_prompt'=>'sunny daytime, dry streets, cartoonish, lowres, extra limbs, bad face','reference_image_url'=>'assets/demo/ai_cyberpunk_neon.jpg','preview_video_url'=>null,'model_name'=>'Midjourney v6.1','style'=>'Trending AI Art','camera_movement'=>'85mm f/1.4 Cine Prime','lighting'=>'Neon Rain Volumetric Reflections','seed'=>'1502326','duration_text'=>'Static','tags'=>'Cyberpunk, Neon Rain, Holographic, Shinjuku Night','is_active'=>1,'display_order'=>6],
        ['id'=>'photo_cyber_samurai','type'=>'photo','title'=>'Cyber Samurai Ronin 2099','category'=>'Trending','prompt'=>'Masterpiece cinematic cyberpunk portrait of a legendary cyber-samurai ronin standing atop a rain-soaked Neo-Kyoto skyscraper rooftop overlooking an endless neon metropolis. Matte-black carbon-fiber samurai armor with glowing crimson LED trim. Half-face titanium Oni demon mask with glowing vent ports. Energized katana blade radiating brilliant electric cyan plasma into the night air. 8K ray-traced reflections, octane render, stunning cinematic composition.','negative_prompt'=>'traditional wooden katana, medieval armor, flat lighting, blurry face, bad hands','reference_image_url'=>'assets/demo/ai_cyber_samurai.jpg','preview_video_url'=>null,'model_name'=>'Flux.1 Pro','style'=>'Trending AI Art','camera_movement'=>'70mm f/2.0 Anamorphic','lighting'=>'Cyan Plasma Blade & Red LED Rim Light','seed'=>'1586047','duration_text'=>'Static','tags'=>'Cyber Samurai, LED Oni Mask, Neon Katana, Carbon Armor, Neo-Tokyo','is_active'=>1,'display_order'=>7],
        ['id'=>'photo_trending_golden_glow','type'=>'photo','title'=>'Golden Hour Dream','category'=>'Trending','prompt'=>'Breathtaking sun-drenched golden hour portrait taken in a wild blooming meadow during peak sunset. Low golden sun directly behind the subject producing magnificent warm halation, golden rim lighting tracing every strand of wind-tousled hair. Floating dust motes and dandelion seeds illuminated like tiny embers in the amber sunlight. 85mm f/1.2 lens, creamy circular optical bokeh, pastel warm peach and honey color grading, Vogue editorial quality, photorealistic 8K UHD.','negative_prompt'=>'overcast, harsh shadows, cold blue lighting, over-retouched skin, plastic','reference_image_url'=>'assets/demo/tmpl-golden-hour.jpg','preview_video_url'=>null,'model_name'=>'Flux.1 Dev','style'=>'Trending AI Art','camera_movement'=>'85mm f/1.2 USM Portrait Lens','lighting'=>'Backlit Low Sun with Golden Halation','seed'=>'1669768','duration_text'=>'Static','tags'=>'Golden Hour, Sun flare, Boho Glow, Warm Cinematic','is_active'=>1,'display_order'=>8],
        ['id'=>'photo_trending_seoul_night','type'=>'photo','title'=>'Seoul Neon Night Market','category'=>'Trending','prompt'=>'Candid nighttime editorial street portrait in the bustling neon-drenched night markets of Hongdae, Seoul. Contemporary oversized Korean fashion, wool trench coat and layered silver chain jewelry. Glowing red and yellow pojangmacha tent lighting mingling with vibrant Korean street signage. Rain mist creating a shimmering glow on the damp pavement, Sony A7R V with 50mm f/1.2 GM lens, cinematic K-drama film grade.','negative_prompt'=>'daytime, empty street, horror lighting, blurry, distorted features','reference_image_url'=>'assets/demo/ai_neon_geisha.jpg','preview_video_url'=>null,'model_name'=>'Midjourney v6.1','style'=>'Trending AI Art','camera_movement'=>'50mm f/1.2 Noctilux','lighting'=>'Warm Tungsten Lanterns & Wet Street Bokeh','seed'=>'1753489','duration_text'=>'Static','tags'=>'K-Drama, Seoul Market, Warm Lanterns, Street Food Bokeh, Winter Coat','is_active'=>1,'display_order'=>9],
        ['id'=>'photo_trending_kpop_stage','type'=>'photo','title'=>'K-Pop Idol Stage Spotlight','category'=>'Trending','prompt'=>'Electrifying live K-Pop stadium concert stage portrait, charismatic idol caught mid-performance under dramatic crisscrossing laser beams and sweeping arena stage spotlights. Custom avant-garde stage outfit with Swarovski crystals, metallic embroidery, and high-shine patent leather. Beads of perspiration glistening under intense magenta, violet, and gold stage lights, energetic facial expression, high-speed confetti bursting in the air, 8K concert photography.','negative_prompt'=>'dark amateur photo, noisy background, red eye, awkward pose, blurry microphone','reference_image_url'=>'assets/demo/tmpl-hype-reel.jpg','preview_video_url'=>null,'model_name'=>'Flux.1 Pro','style'=>'Trending AI Art','camera_movement'=>'135mm f/1.8 Concert Telephoto','lighting'=>'Stadium High-Intensity Followspot','seed'=>'1837210','duration_text'=>'Static','tags'=>'K-Pop, Concert Stage, Glitter Eyes, Stadium Spotlights, Idol','is_active'=>1,'display_order'=>10],

        // ── Editorial ──
        ['id'=>'photo_editorial_prismatic_crystal','type'=>'photo','title'=>'Prismatic Crystal Rainbow','category'=>'Editorial','prompt'=>'Avant-garde high-fashion editorial portrait, subject photographed through a heavy multi-faceted optical crystal prism. Beams of natural sunlight splitting into brilliant rainbow chromatic caustics, kaleidoscopic flares, and vivid color bands cascading across high-fashion makeup and porcelain skin. Bold sculptural glass jewelry reflecting liquid spectrums of violet, emerald, and amber light. High-end Vogue cover aesthetic, shot on medium format Phase One 150MP camera, award-winning editorial lighting.','negative_prompt'=>'blurry, bad eyes, artificial plastic skin, dirty studio, harsh shadows','reference_image_url'=>'assets/demo/ai_prismatic_crystal.jpg','preview_video_url'=>null,'model_name'=>'Flux.1 Pro','style'=>'Editorial AI Art','camera_movement'=>'Hasselblad HC 100mm f/2.2','lighting'=>'Optical Crystal Prism Rainbow Caustics','seed'=>'1920931','duration_text'=>'Static','tags'=>'Optical Prism, Rainbow Caustics, Dewy Beauty, Hasselblad, Clean Studio','is_active'=>1,'display_order'=>11],
        ['id'=>'photo_editorial_haute_couture','type'=>'photo','title'=>'Avant-Garde Chrome Fashion','category'=>'Editorial','prompt'=>'Paris Fashion Week haute couture editorial portrait, model wearing a groundbreaking sculptural gown crafted from molded mirror-polished chrome and pleated midnight-black silk taffeta. High architectural collar, dark plum high-gloss lips and graphic metallic eyeliner. Dramatic Caravaggio chiaroscuro side lighting against a stark minimalist concrete architectural set. Crisp reflections of the runway spotlights bouncing off the polished chrome bodice, 8K masterwork fashion photography.','negative_prompt'=>'casual clothing, messy background, flat lighting, amateur photography','reference_image_url'=>'assets/demo/ai_fashion_editorial.jpg','preview_video_url'=>null,'model_name'=>'Midjourney v6.1','style'=>'Editorial AI Art','camera_movement'=>'85mm f/1.4 Art Lens','lighting'=>'High-Contrast Sculptural Studio Softbox','seed'=>'2004652','duration_text'=>'Static','tags'=>'Vogue Editorial, Chrome Armor, Sculptural Fashion, Minimalist','is_active'=>1,'display_order'=>12],
        ['id'=>'photo_editorial_paris_midnight','type'=>'photo','title'=>'Midnight Paris Haute Couture','category'=>'Editorial','prompt'=>'Romantic Parisian midnight cinematic portrait on the Pont Alexandre III bridge over the Seine River. Soft rain creating reflective wet cobblestones under the glow of ornate golden Belle Époque lampposts. Chic belted camel cashmere coat with silk scarf gently billowing in the river breeze, silhouetted Paris architecture with distant golden lights. Moody deep navy and warm amber color palette, vintage French New Wave cinema atmosphere, 8K resolution.','negative_prompt'=>'crowded tourists, daylight, cheap fabric, blurry architectural lines','reference_image_url'=>'assets/demo/ai_fashion_editorial.jpg','preview_video_url'=>null,'model_name'=>'Midjourney v6.1','style'=>'Editorial AI Art','camera_movement'=>'50mm f/1.2 Prime','lighting'=>'Warm Parisian Streetlamp & Moonlight','seed'=>'2172094','duration_text'=>'Static','tags'=>'Paris Haute Couture, Eiffel Tower Night, Black Silk Dress, Chic','is_active'=>1,'display_order'=>13],
        ['id'=>'photo_editorial_vogue_minimal','type'=>'photo','title'=>'Minimalist Black & White Vogue','category'=>'Editorial','prompt'=>'Iconic black and white Vogue studio portrait, timeless minimalist aesthetic. Striking chiaroscuro lighting sculpting the cheekbones, jawline, and collarbones with deep rich charcoal shadows and luminous soft highlights. Elegant high-neck black turtleneck sweater, direct piercing gaze into the camera lens. Immaculate skin texture with fine pores, shot on Kodak Tri-X 400 black and white film with silver gelatin print tonality.','negative_prompt'=>'color, muddy gray tones, low contrast, washed out blacks, noise','reference_image_url'=>'assets/demo/ai_film_noir.jpg','preview_video_url'=>null,'model_name'=>'Midjourney v6.1','style'=>'Editorial AI Art','camera_movement'=>'85mm f/1.8 Leica Summicron','lighting'=>'Dramatic Single Key Fresnel Spotlight','seed'=>'2339536','duration_text'=>'Static','tags'=>'Black and White, High Contrast, Vogue Italia, Timeless Minimal','is_active'=>1,'display_order'=>14],
        ['id'=>'photo_popular_urban_street','type'=>'photo','title'=>'Urban Streetwear Editorial','category'=>'Editorial','prompt'=>'High-energy modern streetwear lifestyle portrait set in downtown Brooklyn at twilight. Oversized distressed vintage graphic hoodie, utility cargo vest, limited-edition hype sneakers, seated on an industrial steel fire escape. Distant yellow taxi headlights and storefront neon signs casting warm amber and cool slate-blue contrast. Gritty urban textures, candid street culture vibe, captured on 35mm Leica M11 with Summilux 35mm f/1.4 lens, authentic filmic grain.','negative_prompt'=>'nature background, pastel colors, vintage sepia, blurry footwear','reference_image_url'=>'assets/demo/tmpl-urban-street.jpg','preview_video_url'=>null,'model_name'=>'Flux.1 Schnell','style'=>'Editorial AI Art','camera_movement'=>'35mm f/1.4 Wide Prime','lighting'=>'Direct Ring Flash with Falloff','seed'=>'2088373','duration_text'=>'Static','tags'=>'Streetwear, Urban Gritty, Editorial Fashion, Hypebeast','is_active'=>1,'display_order'=>15],

        // ── Sci-Fi & Cyberpunk ──
        ['id'=>'photo_sci_fi_astronaut','type'=>'photo','title'=>'Cosmic Nebula Astronaut','category'=>'Sci-Fi','prompt'=>'Epic cinematic deep-space astronaut portrait, subject wearing a weathered high-tech extravehicular spacesuit with detailed life-support modules and thermal insulation fabric. Mirrored gold-coated visor reflecting a swirling celestial nebula of violet stardust, magenta cosmic dust clouds, and brilliant distant star clusters. Volumetric stellar light illuminating the helmet rim with icy blue and cosmic purple tones, deep obsidian cosmos background, shot on Panavision 70mm lens, 8K photorealism.','negative_prompt'=>'earth background, cracked glass, cartoon suit, muddy textures, bad reflections','reference_image_url'=>'assets/demo/ai_cosmic_astronaut.jpg','preview_video_url'=>null,'model_name'=>'Flux.1 Pro','style'=>'Sci-Fi AI Art','camera_movement'=>'28mm Cosmic Wide Angle','lighting'=>'Internal Visor LED Glow & Nebula Starlight','seed'=>'2423257','duration_text'=>'Static','tags'=>'Astronaut, Cosmic Nebula, Starlight, Deep Space, 8K','is_active'=>1,'display_order'=>16],
        ['id'=>'photo_cyberpunk_neon_geisha','type'=>'photo','title'=>'Neo-Tokyo Cyber Geisha','category'=>'Cyberpunk','prompt'=>'Futuristic cyberpunk neo-geisha portrait in an upscale Neo-Tokyo sky-lounge. Traditional porcelain white face makeup contrasting with intricate glowing gold fiber-optic circuitry patterns tracing down the neck and collarbone. Elaborate sculptural hair adorned with metallic kanzashi hairpins and glowing neon fiber cables. Holographic smart-fabric kimono shimmering between iridescent turquoise and hot magenta. Cybernetic mechanical fingers holding a delicate porcelain sake cup, rainy skyline visible through floor-to-ceiling windows, 8K cinematic detail.','negative_prompt'=>'traditional historic setting, dull colors, plastic skin, bad hands','reference_image_url'=>'assets/demo/ai_neon_geisha.jpg','preview_video_url'=>null,'model_name'=>'Midjourney v6.1','style'=>'Cyberpunk AI Art','camera_movement'=>'50mm f/1.4 Cine Prime','lighting'=>'Fiber-Optic Glow & Tokyo Neon Backlight','seed'=>'2506978','duration_text'=>'Static','tags'=>'Cyber Geisha, Neon Kimono, Shinjuku Night, Hologram','is_active'=>1,'display_order'=>17],
        ['id'=>'photo_cyberpunk_neon_noir','type'=>'photo','title'=>'Neon Noir Detective','category'=>'Cyberpunk','prompt'=>'Moody cyberpunk neon-noir detective portrait, solitary figure in a wet trench coat with an upturned collar standing under a flickering holographic neon sign in a desolate industrial alleyway. Dense cigarette smoke curling upwards through heavy blue rain and amber light beams. Hard rain droplets dripping from the brim of a fedora hat, cybernetic eye enhancement casting a faint scanning reticle into the shadows, dramatic film noir low-key lighting with high-contrast shadows, 8K masterwork.','negative_prompt'=>'sunny daytime, clean dry streets, bright comedy mood, lowres','reference_image_url'=>'assets/demo/ai_cyberpunk_neon.jpg','preview_video_url'=>null,'model_name'=>'Flux.1 Dev','style'=>'Cyberpunk AI Art','camera_movement'=>'35mm Anamorphic 2x Squeeze','lighting'=>'Moody Volumetric Steam & Amber Neon Sign','seed'=>'2590699','duration_text'=>'Static','tags'=>'Neon Noir, Blade Runner, Moody Rain, Shadows','is_active'=>1,'display_order'=>18],
        ['id'=>'photo_scifi_orbital_commander','type'=>'photo','title'=>'Orbital Fleet Commander','category'=>'Sci-Fi','prompt'=>'Authoritative sci-fi orbital fleet commander portrait on the command bridge of an interstellar dreadnought starship. Crisp military tactical officer uniform with glowing rank insignias and holographic telemetry wrist gauntlet. Massive panoramic observation windows overlooking a swirling gas giant planet with concentric golden rings and orbiting star cruisers. Soft ambient glow from blue control console screens, 8K cinematic lighting.','negative_prompt'=>'medieval, fantasy, lowres, flat walls, blurry holograms','reference_image_url'=>'assets/demo/ai_cosmic_astronaut.jpg','preview_video_url'=>null,'model_name'=>'Flux.1 Pro','style'=>'Sci-Fi AI Art','camera_movement'=>'50mm f/1.4 Anamorphic','lighting'=>'Cyan Holographic UI Glow & Planet Reflection','seed'=>'2674420','duration_text'=>'Static','tags'=>'Sci-Fi Commander, Starship Bridge, Holographic Starmap, Uniform','is_active'=>1,'display_order'=>19],
        ['id'=>'photo_scifi_cyber_hacker','type'=>'photo','title'=>'Underground Cyber Hacker','category'=>'Cyberpunk','prompt'=>'Intense underground netrunner hacker portrait in a hidden tech bunker surrounded by flickering multi-monitor displays showing cascading green terminal code, network topographies, and decrypted data streams. Dark oversized hoodie with hood pulled low, reflective holographic glasses, fingers poised over a custom mechanical cyberpunk keyboard, blue and green ambient LED glow, dense atmospheric room haze, 8K cinematic realism.','negative_prompt'=>'clean corporate office, daylight, cartoonish, low detail','reference_image_url'=>'assets/demo/ai_cyber_samurai.jpg','preview_video_url'=>null,'model_name'=>'SDXL Turbo','style'=>'Cyberpunk AI Art','camera_movement'=>'35mm f/1.8 Street Prime','lighting'=>'Multi-Monitor Phosphor Glow & Rim Light','seed'=>'2841862','duration_text'=>'Static','tags'=>'Netrunner, Matrix Code, Hacker Den, Cyberdeck, Hoodie','is_active'=>1,'display_order'=>20],

        // ── Fantasy ──
        ['id'=>'photo_fantasy_nordic_viking','type'=>'photo','title'=>'Nordic Viking Shieldmaiden','category'=>'Fantasy','prompt'=>'Fierce historical Nordic Viking shieldmaiden portrait standing on a windswept icy fjord bluff in Scandinavia. Weathered braided blonde hair woven with bone beads, war paint across the eyes in charcoal and woad blue. Heavy tailored fur cloak over embossed leather lamellar armor with bronze battle brooches. Holding a battle-scarred round wooden shield with carved dragon motifs, snow flurries swirling in the frigid northern gale, overcast moody Arctic sky, 8K photorealistic detail.','negative_prompt'=>'horns on helmet, modern cosmetics, studio backdrop, cartoonish, blurry','reference_image_url'=>'assets/demo/ai_viking_warrior.jpg','preview_video_url'=>null,'model_name'=>'Flux.1 Pro','style'=>'Fantasy AI Art','camera_movement'=>'85mm f/1.4 Telephoto Portrait','lighting'=>'Cold Arctic Morning Sun & Mountain Mist','seed'=>'2925583','duration_text'=>'Static','tags'=>'Viking Warrior, Shieldmaiden, Nordic Fjord, Runic War Paint, Wolf Fur','is_active'=>1,'display_order'=>21],
        ['id'=>'photo_fantasy_enchanted_elf','type'=>'photo','title'=>'Bioluminescent Woodland Elf','category'=>'Fantasy','prompt'=>'Bioluminescent woodland elf royal portrait deep within an ancient mystical twilight forest. Pointed elegant ears adorned with delicate silver filigree cuffs, cascading silver hair woven with glowing starlight blossoms and emerald ivy vines. Translucent ethereal skin glowing with soft inner fairy light, wearing an organic dress woven of luminous leaves and shimmering moon-spider silk. Giant ancient moss-covered trees, floating magical pollen embers, and gentle sunbeams piercing misty canopy, 8K high-fantasy concept art.','negative_prompt'=>'modern clothes, human ears, harsh daylight, desert, blurry artwork','reference_image_url'=>'assets/demo/ai_fantasy_elf.jpg','preview_video_url'=>null,'model_name'=>'Flux.1 Dev','style'=>'Fantasy AI Art','camera_movement'=>'85mm f/1.2 Dreamy Portrait','lighting'=>'Bioluminescent Flora & Firefly Glow','seed'=>'3009304','duration_text'=>'Static','tags'=>'Elven Maiden, Bioluminescence, Enchanted Forest, Fairytale','is_active'=>1,'display_order'=>22],
        ['id'=>'photo_fantasy_celestial_angel','type'=>'photo','title'=>'Celestial Seraph Golden Angel','category'=>'Fantasy','prompt'=>'Magnificent celestial seraph angel portrait in heavenly cloudscapes at dawn. Massive hyper-detailed feathered wings spanning outward, each feather tipped with luminous iridescent gold foil and glowing divine light. Flowing pure white gossamer robes embroidered with celestial constellations in silver thread, glowing radiant halo of pure sunlight hovering above the head. Golden sunrise clouds stretching to the horizon, divine godrays breaking through atmospheric mist, 8K resolution.','negative_prompt'=>'demon, dark gothic, plastic wings, flat lighting, lowres','reference_image_url'=>'assets/demo/ai_prismatic_crystal.jpg','preview_video_url'=>null,'model_name'=>'Flux.1 Pro','style'=>'Fantasy AI Art','camera_movement'=>'70-200mm f/2.8 Telephoto','lighting'=>'Heavenly Godrays & Radiant Golden Halo','seed'=>'3176746','duration_text'=>'Static','tags'=>'Angel Wings, Celestial Seraph, Halo of Light, Floating Feathers, Heavenly','is_active'=>1,'display_order'=>23],
        ['id'=>'photo_fantasy_moon_priestess','type'=>'photo','title'=>'Celtic Silver Moon Priestess','category'=>'Fantasy','prompt'=>'Mystical Celtic moon priestess portrait inside an ancient prehistoric stone circle beneath a radiant full silver moon. Hooded midnight-blue velvet cloak lined with silver silk, holding an ornate silver staff crowned with a glowing moonstone orb. Silver lunar crescent tiara, delicate glowing runic tattoos tracing the temples and hands, soft night mist rolling over mossy megalith stones, eerie silver moonbeams illuminating the serene face, 8K high-fantasy photorealism.','negative_prompt'=>'daytime, modern cities, electric lighting, deformed hands, cartoon','reference_image_url'=>'assets/demo/ai_fantasy_elf.jpg','preview_video_url'=>null,'model_name'=>'Midjourney v6.1','style'=>'Fantasy AI Art','camera_movement'=>'50mm f/1.2 Nocturnal Lens','lighting'=>'Cool Full Moon Chiaroscuro & Lunar Glow','seed'=>'3260467','duration_text'=>'Static','tags'=>'Moon Priestess, Silver Tiara, Stonehenge, Moonlit Fog, Celtic','is_active'=>1,'display_order'=>24],

        // ── Vintage ──
        ['id'=>'photo_new_steampunk_inventor','type'=>'photo','title'=>'Steampunk Victorian Inventor','category'=>'Vintage','prompt'=>'Intricate Victorian steampunk inventor portrait inside a cluttered brass clockwork laboratory filled with rotating gears, ticking pendulum clocks, and bubbling copper distillation retorts. Leather artisan apron over rolled-up linen shirt sleeves, multi-lens brass magnifying goggles, brass mechanical gauntlet with miniature pressure gauges. Atmospheric amber sunlight streaming through dusty industrial factory windows, warm sepia tones, cinematic steam plumes, 8K vintage aesthetic.','negative_prompt'=>'modern electronics, plastic, neon cyan, flat studio background, cartoon','reference_image_url'=>'assets/demo/ai_steampunk_inventor.jpg','preview_video_url'=>null,'model_name'=>'Flux.1 Pro','style'=>'Vintage AI Art','camera_movement'=>'50mm f/1.4 Vintage Zeiss Lens','lighting'=>'Warm Filament Bulbs & Brass Reflections','seed'=>'3344188','duration_text'=>'Static','tags'=>'Steampunk, Brass Goggles, Clockwork Gears, Copper Armature, Victorian Workshop','is_active'=>1,'display_order'=>25],
        ['id'=>'photo_vintage_dark_academia','type'=>'photo','title'=>'Gothic Dark Academia','category'=>'Vintage','prompt'=>'Atmospheric Gothic dark academia portrait inside an ancient university library surrounded by floor-to-ceiling mahogany bookshelves stacked with leather-bound antique grimoires. Tailored tweed wool blazer, cable-knit turtleneck sweater, and tortoiseshell round spectacles, reading an aged manuscript by warm flickering candlelight. Stained glass gothic arched windows casting jewel-toned reflections onto polished parquet floor, scholarly intellectual mood, warm rich amber and mahogany palette, 8K cinematic portrait.','negative_prompt'=>'modern gadgets, neon lights, cheap plastic, flat digital lighting','reference_image_url'=>'assets/demo/ai_dark_academia.jpg','preview_video_url'=>null,'model_name'=>'Midjourney v6.1','style'=>'Vintage AI Art','camera_movement'=>'50mm f/1.4 Planar','lighting'=>'Warm Chiaroscuro Candlelight & Stained Glass Sunbeam','seed'=>'3427909','duration_text'=>'Static','tags'=>'Dark Academia, Gothic Library, Tweed & Glasses, Chiaroscuro','is_active'=>1,'display_order'=>26],
        ['id'=>'photo_vintage_90s_kodak','type'=>'photo','title'=>'90s Kodak Gold 200','category'=>'Vintage','prompt'=>'Nostalgic 1990s analog 35mm candid portrait shot on Kodak Gold 200 film stock. Subject lounging casually on a vintage floral sofa in a sunlit apartment, wearing vintage high-waisted denim jeans and an oversized band tee. Warm golden color saturation, gentle halation around window highlights, authentic soft grain structure, authentic 90s indie cinema aesthetic, relaxed candid human moment, 8K analog photography.','negative_prompt'=>'digital perfection, HDR, plastic skin, cold blue cast','reference_image_url'=>'assets/demo/tmpl-retro-90s.jpg','preview_video_url'=>null,'model_name'=>'Flux.1 Schnell','style'=>'Vintage AI Art','camera_movement'=>'Contax T2 38mm f/2.8 Carl Zeiss','lighting'=>'Warm Golden Sunlight with Film Halation','seed'=>'3511630','duration_text'=>'Static','tags'=>'Kodak Gold, 35mm Film, 90s Nostalgia, Candid','is_active'=>1,'display_order'=>27],

        // ── Anime ──
        ['id'=>'photo_popular_anime','type'=>'photo','title'=>'Cherry Blossom Anime','category'=>'Anime','prompt'=>'Vibrant modern anime art portrait in the signature style of Makoto Shinkai and CoMix Wave Films. Stunning anime girl with expressive violet eyes and wind-swept flowing hair, standing on a Tokyo pedestrian bridge at golden hour sunset. Swirling pink cherry blossom sakura petals drifting through the air, hyper-detailed volumetric clouds glowing with peach, orange, and purple sunset light, photorealistic anime background, masterwork digital anime illustration, 8K resolution.','negative_prompt'=>'photorealistic human, 3D clay, dark horror, messy lineart, watermark','reference_image_url'=>'assets/demo/ai_anime_art.jpg','preview_video_url'=>null,'model_name'=>'NijiJourney v6','style'=>'Anime AI Art','camera_movement'=>'Makoto Shinkai Digital Cinema 35mm','lighting'=>'Golden Hour Anime Sunbeams','seed'=>'3762793','duration_text'=>'Static','tags'=>'Anime Illustration, Cherry Blossoms, Makoto Shinkai, Sunlit','is_active'=>1,'display_order'=>28],
        ['id'=>'photo_anime_sakura_watercolor','type'=>'photo','title'=>'Imperial Sakura Watercolor','category'=>'Anime','prompt'=>'Traditional Japanese watercolor and sumi-e ink anime portrait, delicate ink brushstrokes delineating a serene samurai maiden amidst blooming sakura branches. Soft transparent watercolor washes in rose pink, cerulean blue, and tea-stained ivory diffusing into handmade washi rice paper texture. Splash ink splatter effects, elegant calligraphic outlines, peaceful poetic Japanese aesthetic, award-winning anime fine art.','negative_prompt'=>'rough digital smudge, low quality, deformed hands, harsh black lines','reference_image_url'=>'assets/demo/ai_watercolor_dream.jpg','preview_video_url'=>null,'model_name'=>'Midjourney v6.1','style'=>'Anime AI Art','camera_movement'=>'Traditional Sumi-e & Watercolor Fine Art','lighting'=>'Soft Watercolor Paper Diffused Daylight','seed'=>'3846514','duration_text'=>'Static','tags'=>'Watercolor Wash, Cherry Blossoms, Cranes, Gold Leaf, Poetic','is_active'=>1,'display_order'=>29],
        ['id'=>'photo_anime_lofi_aesthetic','type'=>'photo','title'=>'Lo-Fi Sunset Window Anime','category'=>'Anime','prompt'=>'Cozy lo-fi hip-hop study beats anime portrait, subject wearing oversized headphones leaning on a wooden study desk beside a large rain-streaked window at twilight. Soft warm desk lamp illuminating open notebook, coffee mug with rising steam, and a sleeping tabby cat curled on the windowsill. Distant city lights sparkling in soft blurred pastel circles through the rain, calm relaxing lo-fi aesthetic, warm muted color palette, 8K anime illustration.','negative_prompt'=>'gritty violence, harsh cold lighting, photorealism, bad hands','reference_image_url'=>'assets/demo/tmpl-retro-90s.jpg','preview_video_url'=>null,'model_name'=>'Midjourney v6.1','style'=>'Anime AI Art','camera_movement'=>'35mm Studio Ghibli Soft Focus','lighting'=>'Warm Golden Hour Window Sunlight','seed'=>'4181398','duration_text'=>'Static','tags'=>'Lo-Fi Girl, Sunset Window, Cozy Room, Headphones, Cat','is_active'=>1,'display_order'=>30],

        // ── 3D / Pixar ──
        ['id'=>'photo_new_3d_pixar','type'=>'photo','title'=>'3D Animated Character','category'=>'3D Pixar','prompt'=>'Charming 3D animated character portrait in the signature style of modern Pixar and Disney Animation Studios. Expressive, oversized warm brown eyes with lifelike light catchlights, cheerful charismatic smile, individually styled strands of soft stylized hair catching the light. Soft peach skin with subtle subsurface scattering and cute freckles, wearing a cozy knitted wool sweater with realistic yarn fuzz and weave. Warm inviting studio portrait lighting, soft blurred pastel background, award-winning 3D feature film quality, 8K Octane render.','negative_prompt'=>'photorealistic human, uncanny valley, harsh shadows, flat shading, 2D drawing','reference_image_url'=>'assets/demo/ai_3d_render.jpg','preview_video_url'=>null,'model_name'=>'Midjourney v6.1 - Niji','style'=>'3D Pixar AI Art','camera_movement'=>'50mm Cinema 4D Stylized Camera','lighting'=>'Three-Point Soft Studio Light','seed'=>'4265119','duration_text'=>'Static','tags'=>'3D Animated, Whimsical, Subsurface Scattering, Pixar Style','is_active'=>1,'display_order'=>31],

        // ── AI Video Presets ──
        ['id'=>'video_cinematic_city_night','type'=>'video','title'=>'Cinematic City Night Drive','category'=>'Trending','prompt'=>'Cinematic night-drive timelapse through a glowing neon-soaked city, ultra-smooth dolly movement, ultra-wide anamorphic lens, high-speed light trails from passing vehicles. Rain-slicked streets reflecting brilliant LED shop signs and traffic lights. Camera pushes slowly forward through the wet urban canyons, atmospheric motion blur on background, sharp foreground neon glow, photorealistic 8K video.','negative_prompt'=>'daytime, static camera, blurry focus, low resolution, cartoonish','reference_image_url'=>'assets/demo/ai_cyberpunk_neon.jpg','preview_video_url'=>'https://cdn.pixabay.com/video/2016/09/15/5107-183361061_large.mp4','model_name'=>'OpenAI Sora','style'=>'Cinematic','camera_movement'=>'Smooth Cinematic Dolly Push','lighting'=>'Neon Wet Street Reflections','seed'=>'5001001','duration_text'=>'8s','tags'=>'Night Drive, City, Cinematic, Anamorphic, 4K','is_active'=>1,'display_order'=>50],
        ['id'=>'video_golden_hour_beach','type'=>'video','title'=>'Golden Hour Beach Waves','category'=>'Nature & Travel','prompt'=>'Breathtaking slow-motion golden hour ocean beach scene, gentle rolling waves washing over white sand, capturing each droplet of foam and glistening water in extreme slow-motion at 240fps. Warm golden sun low on the horizon painting the ocean surface in molten amber and rose gold. Ultra-smooth camera dolly movement, cinematic wide lens, peaceful ambient ocean sounds, photorealistic 8K video.','negative_prompt'=>'storm, overcast, dull colors, rough waves, low resolution','reference_image_url'=>'assets/demo/tmpl-golden-hour.jpg','preview_video_url'=>'https://cdn.pixabay.com/video/2015/09/06/765-138428574_large.mp4','model_name'=>'Runway Gen-3 Alpha','style'=>'Nature Cinematic','camera_movement'=>'Ultra-Slow Dolly Lateral','lighting'=>'Golden Sunset Warm Side Light','seed'=>'5002002','duration_text'=>'10s','tags'=>'Ocean, Beach Waves, Golden Hour, Slow Motion, Aerial','is_active'=>1,'display_order'=>51],
        ['id'=>'video_particle_galaxy_zoom','type'=>'video','title'=>'Galaxy Portal Particle Zoom','category'=>'Sci-Fi','prompt'=>'Epic deep space journey sequence, camera hurtling at high speed through a swirling cosmic nebula of electric violet stardust and brilliant cyan plasma. Hyper-detailed luminous star particles rush past in streaks of light, a spiral galaxy grows rapidly in the center frame. Dynamic motion blur on peripheral stars, depth of field pulling between foreground particles and distant nebula structures. Photorealistic space VFX, 8K resolution.','negative_prompt'=>'dark muddy colors, static shot, low resolution stars, cartoony CGI','reference_image_url'=>'assets/demo/ai_cosmic_astronaut.jpg','preview_video_url'=>'https://cdn.pixabay.com/video/2016/06/15/3573-170563044_large.mp4','model_name'=>'OpenAI Sora','style'=>'Cosmic VFX','camera_movement'=>'High-Speed Forward Zoom Through Nebula','lighting'=>'Luminous Stellar Particle Glow','seed'=>'5003003','duration_text'=>'8s','tags'=>'Galaxy, Space, Nebula, Particles, Sci-Fi VFX','is_active'=>1,'display_order'=>52],
        ['id'=>'video_autumn_forest_walk','type'=>'video','title'=>'Autumn Forest Walk','category'=>'Nature & Travel','prompt'=>'Serene slow-motion walk through a stunning autumn forest with towering trees draped in brilliant red, orange, and golden foliage. Camera slowly pushes forward through a narrow leaf-carpeted path as warm sunlight streams through the colorful canopy, casting dappled golden pools of light on the forest floor. Dozens of fall leaves gently drift past in the foreground. Ultra-sharp depth of field with creamy background bokeh, photorealistic 8K nature video.','negative_prompt'=>'summer green, dark night, rain, flat gray sky, static shot','reference_image_url'=>'assets/demo/tmpl-golden-hour.jpg','preview_video_url'=>'https://cdn.pixabay.com/video/2019/04/14/22964-330877867_large.mp4','model_name'=>'Luma Dream Machine','style'=>'Nature Cinematic','camera_movement'=>'Steady Forward Dolly Push','lighting'=>'Dappled Autumn Canopy Sunlight','seed'=>'5004004','duration_text'=>'12s','tags'=>'Autumn Leaves, Forest Walk, Cinematic, Depth of Field, Nature','is_active'=>1,'display_order'=>53],
        ['id'=>'video_neon_city_aerial','type'=>'video','title'=>'Neon City Aerial Flyover','category'=>'Trending','prompt'=>'Breathtaking cinematic aerial drone flyover of a futuristic neon-lit megacity skyline at night, banking gracefully over illuminated skyscrapers and intersecting highways of glowing vehicle light trails. Holographic billboard advertisements casting colorful reflections onto the wet rooftops below. Camera banks smoothly through a dramatic S-curve revealing the full city sprawl, ultra-wide anamorphic lens, photorealistic 8K aerial video.','negative_prompt'=>'daytime, dark dull city, low resolution, static camera, cartoonish','reference_image_url'=>'assets/demo/ai_cyberpunk_neon.jpg','preview_video_url'=>'https://cdn.pixabay.com/video/2020/07/26/46041-444673472_large.mp4','model_name'=>'Runway Gen-3 Alpha','style'=>'Urban Cinematic','camera_movement'=>'Cinematic Aerial Drone Banking S-Curve','lighting'=>'City Neon & LED Street Light Glow','seed'=>'5005005','duration_text'=>'10s','tags'=>'Aerial, City Night, Drone Shot, Neon, Light Trails','is_active'=>1,'display_order'=>54],
        ['id'=>'video_fire_abstract','type'=>'video','title'=>'Flowing Fire Abstract','category'=>'Abstract','prompt'=>'Ultra-stunning abstract fire art video sequence, captivating slow-motion fire tendrils and flame vortices swirling upward in a pitch-black void. Brilliant orange, scarlet, golden-yellow, and electric blue inner-core fire flow choreographed in perfect slow motion. Photorealistic particle simulation of 500K fire particles with subsurface glow and heat shimmer effects. Camera rotates slowly around the flame column, 8K resolution.','negative_prompt'=>'explosion, destruction, dark smoke, poor lighting, CGI cartoon','reference_image_url'=>'assets/demo/tmpl-hype-reel.jpg','preview_video_url'=>'https://cdn.pixabay.com/video/2015/08/10/320-135733823_large.mp4','model_name'=>'Kling AI 1.5','style'=>'Abstract Visual','camera_movement'=>'Slow Orbital Rotation','lighting'=>'Self-Illuminated Firelight Emission','seed'=>'5006006','duration_text'=>'8s','tags'=>'Fire, Abstract, Slow Motion, Particle FX, Visual Art','is_active'=>1,'display_order'=>55],
        ['id'=>'video_ocean_sunset_timelapse','type'=>'video','title'=>'Ocean Sunset Time-Lapse','category'=>'Nature & Travel','prompt'=>'Dramatic ocean sunset time-lapse filmed from a cliff overlooking a sweeping bay. The sun rapidly descends toward the horizon, painting the clouds in explosive cascading colors from brilliant white to deep gold, burning amber, hot magenta, and finally violet twilight. Ocean waves catch the final sunlight in white highlights as the sky transforms above them. Hyper-smooth time-lapse motion, wide anamorphic lens, photorealistic 8K.','negative_prompt'=>'rainy, overcast, dull colors, static shot, low resolution','reference_image_url'=>'assets/demo/tmpl-golden-hour.jpg','preview_video_url'=>'https://cdn.pixabay.com/video/2019/01/10/20517-310133459_large.mp4','model_name'=>'Luma Dream Machine','style'=>'Nature Cinematic','camera_movement'=>'Ultra-Smooth Locked Tripod Timelapse','lighting'=>'Natural Sunset Dynamic Sky Color','seed'=>'5007007','duration_text'=>'15s','tags'=>'Ocean Sunset, Timelapse, Sky Color, Natural Light, Dramatic','is_active'=>1,'display_order'=>56],
        ['id'=>'video_confetti_celebration','type'=>'video','title'=>'Confetti Celebration Burst','category'=>'Trending','prompt'=>'Joyful slow-motion confetti cannon celebration video sequence, thousands of brilliant multi-colored paper confetti pieces and metallic streamers burst outward from the center of frame filling the entire scene in a cascade of color. Deep black background makes every confetti piece pop with vivid saturation. Subject visible in center celebrating with arms raised in victory pose. 240fps extreme slow motion, 8K confetti detail.','negative_prompt'=>'sad, dark, monochrome, low resolution, blur','reference_image_url'=>'assets/demo/tmpl-hype-reel.jpg','preview_video_url'=>'https://cdn.pixabay.com/video/2020/01/17/31130-386657818_large.mp4','model_name'=>'Pika 2.0 Pro','style'=>'Celebration','camera_movement'=>'Locked Wide Slow-Motion Shot','lighting'=>'Bright Even Studio Celebration Lights','seed'=>'5008008','duration_text'=>'5s','tags'=>'Confetti, Celebration, Party, Slow Motion, Happy','is_active'=>1,'display_order'=>57],
    ];

    foreach ($presets as $p) {
        try {
            $existing = Database::fetchOne("SELECT id FROM ai_presets WHERE id = ?", [$p['id']]);
            if ($existing) {
                Database::query(
                    "UPDATE ai_presets SET type=?, title=?, category=?, prompt=?, negative_prompt=?, reference_image_url=?,
                     preview_video_url=?, model_name=?, style=?, camera_movement=?, lighting=?, seed=?,
                     duration_text=?, tags=?, is_active=?, display_order=?, updated_at=NOW() WHERE id=?",
                    [$p['type'],$p['title'],$p['category'],$p['prompt'],$p['negative_prompt'],$p['reference_image_url'],
                     $p['preview_video_url'],$p['model_name'],$p['style'],$p['camera_movement'],$p['lighting'],$p['seed'],
                     $p['duration_text'],$p['tags'],$p['is_active'],$p['display_order'],$p['id']]
                );
                $updated++;
            } else {
                Database::query(
                    "INSERT INTO ai_presets (id,type,title,category,prompt,negative_prompt,reference_image_url,
                     preview_video_url,model_name,style,camera_movement,lighting,seed,duration_text,tags,is_active,display_order)
                     VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
                    [$p['id'],$p['type'],$p['title'],$p['category'],$p['prompt'],$p['negative_prompt'],$p['reference_image_url'],
                     $p['preview_video_url'],$p['model_name'],$p['style'],$p['camera_movement'],$p['lighting'],$p['seed'],
                     $p['duration_text'],$p['tags'],$p['is_active'],$p['display_order']]
                );
                $inserted++;
            }
        } catch (Throwable $e) {
            // skip failed row
        }
    }

    $total = (int)(Database::fetchOne("SELECT COUNT(*) as c FROM ai_presets")['c'] ?? 0);
    return ['inserted' => $inserted, 'updated' => $updated, 'total' => $total];
}
