#!/usr/bin/env python3
import re
import os

NEW_PRESETS_DART = """    // ── 11. Expanded Pro Presets (20 New Cinematic Styles) ──
    const AiPhotoPresetEntity(
      id: 'photo_cyber_biker_neo_shibuya',
      title: 'Neo-Shibuya Cyber Biker',
      category: 'Cyberpunk',
      badgeText: '🏍️ SPEED DEMON',
      referenceImagePath: 'assets/demo/ai_cyberpunk_neon.jpg',
      likesCount: 9840,
      aspectRatio: '3:4',
      styleKeywords: ['Cyber Biker', 'Shibuya 2099', 'Speed Streaks', 'Kevlar Suit', 'HUD Visor'],
      prompt:
          'Masterpiece 8K cinematic action portrait of an adrenaline-fueled cybernetic motorcycle racer leaning into a sharp neon-slicked turn through Shibuya Crossing 2099. Wearing customized matte-black Kevlar race leathers with embedded blue electro-luminescent telemetry strips, aerodynamic carbon-fiber helmet with mirrored violet visor projecting real-time velocity heads-up display. High-tech hover-bike tail lights casting brilliant red laser streaks across wet reflective asphalt, motion blur in the neon cityscape background with razor-sharp focal clarity on the rider, shot on Sony FX9 with 35mm T1.5 Cine lens, volumetric rain mist, award-winning cinematic action photography.',
      negativePrompt: 'blurry, static pose, day lighting, vintage wooden bike, low quality, bad anatomy, deformed limbs',
      modelRecommendation: 'Midjourney v6.1',
      lightingStyle: 'Streaking Red Laser Lights & Cyan Street Glow',
      cameraLens: '35mm T1.5 Cine High-Speed Lens',
    ),
    const AiPhotoPresetEntity(
      id: 'photo_scifi_deep_space_miner',
      title: 'Asteroid Belt Mining Engineer',
      category: 'Sci-Fi',
      badgeText: '🚀 BELTER',
      referenceImagePath: 'assets/demo/ai_cosmic_astronaut.jpg',
      likesCount: 8430,
      aspectRatio: '3:4',
      styleKeywords: ['Asteroid Miner', 'Exosuit', 'Space Station', 'Industrial Sci-Fi'],
      prompt:
          'Gritty hyper-realistic sci-fi industrial portrait of a veteran asteroid miner inside the airlock chamber of an off-world orbital mining station. Heavy pressurized industrial hazard exosuit with weathered scratches, warning hazard chevrons, heavy hydraulic servo-joints, and pressurized oxygen manifolds. Face visible through reinforced gold-tinted polycarbonate visor, showing sweat streaks, intense tired eyes, and micro-stubble under harsh utilitarian halogen work lights. Giant revolving mining lasers and crystalline asteroid fields visible through thick reinforced glass portal, 8K ultra-detailed Unreal Engine 5 aesthetic.',
      negativePrompt: 'clean pristine spacesuit, white laboratory, cartoon, flat lighting, lowres',
      modelRecommendation: 'Flux.1 Pro',
      lightingStyle: 'Utilitarian Amber Warning Beams & Vacuum Dark',
      cameraLens: '50mm f/1.2 Low-Light Prime',
    ),
    const AiPhotoPresetEntity(
      id: 'photo_cyber_synth_idol',
      title: 'Holographic Cyber Synth Vocalist',
      category: 'Cyberpunk',
      badgeText: '🎤 CYBER IDOL',
      referenceImagePath: 'assets/demo/ai_neon_geisha.jpg',
      likesCount: 9120,
      aspectRatio: '3:4',
      styleKeywords: ['Synth Idol', 'Hologram Notes', 'Fiber-Optic Hair', 'Neo-Seoul'],
      prompt:
          'Stunning futuristic cyber-idol performing live in a floating holographic amphitheater in Neo-Seoul. Translucent glowing cyan hair woven with interactive optical fibers that pulsate to the beat of electronic music, delicate chrome subdermal implants along jawline, futuristic iridescent vinyl corset with glowing equalizer waveforms. Swirling holographic musical notes and neon butterflies radiating from outstretched hands, thousands of glowing light sticks in the blurred arena audience below, brilliant stage laser beams, 8K anime-photorealism hybrid.',
      negativePrompt: 'dull lighting, empty stage, cartoonish, low resolution, bad hands, extra fingers',
      modelRecommendation: 'Midjourney v6.1',
      lightingStyle: 'Arena Laser Beams & Cyan Equalizer Glow',
      cameraLens: '85mm f/1.4 Portrait Telephoto',
    ),
    const AiPhotoPresetEntity(
      id: 'photo_editorial_baroque_pearl',
      title: 'Baroque Pearl & Diamond Empress',
      category: 'Editorial',
      badgeText: '💎 HAUTE JOAILLERIE',
      referenceImagePath: 'assets/demo/ai_fashion_editorial.jpg',
      likesCount: 11240,
      aspectRatio: '3:4',
      styleKeywords: ['Baroque Pearl', 'Diamond Crown', 'Haute Couture', 'Vogue Italia'],
      prompt:
          'Monumental haute couture editorial portrait, high-fashion model wearing an extravagant sculpted crown crafted entirely from thousands of organic freshwater baroque pearls, raw diamonds, and antique platinum filigree. Draped in a structured ivory duchess silk satin cape with high Elizabethan ruff collar. Impeccable porcelain complexion with subtle mother-of-pearl shimmer highlighter, dramatic smoky eyes, lips painted in deep antique ruby satin. Flawless softbox key lighting with delicate silver fill against an opulent dark velvet backdrop, photographed on Phase One XF 150MP camera with Schneider Kreuznach 110mm f/2.8 lens, Vogue Italia cover quality.',
      negativePrompt: 'cheap plastic beads, modern casual clothing, casual snapshot, washed out colors',
      modelRecommendation: 'Flux.1 Pro',
      lightingStyle: 'Chiaroscuro Studio Softbox & Silver Fill',
      cameraLens: 'Schneider Kreuznach 110mm f/2.8',
    ),
    const AiPhotoPresetEntity(
      id: 'photo_editorial_glass_sculpture',
      title: 'Avant-Garde Hand-Blown Glass Couture',
      category: 'Editorial',
      badgeText: '✨ GLASS COUTURE',
      referenceImagePath: 'assets/demo/ai_prismatic_crystal.jpg',
      likesCount: 10450,
      aspectRatio: '3:4',
      styleKeywords: ['Glass Armor', 'Prismatic Caustics', 'Couture', 'Sculptural Art'],
      prompt:
          'Breathtaking conceptual fashion portrait featuring a model adorned in wearable hand-blown iridescent borosilicate glass armor. Translucent curved glass breastplate and crystalline shoulder pauldrons refracting surrounding studio spotlights into fluid prismatic caustics and spectral flares. Underneath, a sheer minimalist charcoal tulle undergarment, striking statuesque pose, slicked wet-look architectural hair, high-fashion contouring. Shot in a minimalist white infinity cove studio with sharp geometric shadow play, masterwork editorial photography, 8K UHD clarity.',
      negativePrompt: 'broken glass, dirty textures, plastic look, ordinary dress, blurry focus',
      modelRecommendation: 'Midjourney v6.1',
      lightingStyle: 'Spectral Prism Caustic Splashes & Sharp Studio Strobe',
      cameraLens: 'Hasselblad 80mm f/1.9 Cine Lens',
    ),
    const AiPhotoPresetEntity(
      id: 'photo_editorial_midnight_gala',
      title: 'Obsidian Velvet Midnight Gala',
      category: 'Editorial',
      badgeText: '🎩 NOIR GALA',
      referenceImagePath: 'assets/demo/ai_dark_academia.jpg',
      likesCount: 8970,
      aspectRatio: '3:4',
      styleKeywords: ['Velvet Tuxedo', 'Midnight Ball', 'Marble Stairs', 'Chandelier'],
      prompt:
          'Dapper high-fashion black-tie portrait of an aristocrat descending a grand sweeping marble staircase of a private European museum at midnight. Wearing a bespoke midnight-black velvet tuxedo jacket with satin peak lapels, tailored cummerbund, antique platinum lapel pin set with black diamonds. Warm golden crystal chandeliers casting rich amber specular highlights on polished marble floors and classical Greek sculptures. Confident, charismatic gaze toward the camera, shallow depth of field, 35mm Leica Monochrom aesthetic with subtle warm split-toning, luxury lifestyle editorial.',
      negativePrompt: 'messy room, casual clothes, daytime, low resolution, bad hands, washed out blacks',
      modelRecommendation: 'Flux.1 Dev',
      lightingStyle: 'Grand Chandelier Amber Glow & Marble Specular Bounce',
      cameraLens: 'Leica Summilux-M 50mm f/1.4',
    ),
    const AiPhotoPresetEntity(
      id: 'photo_anime_shadow_monarch',
      title: 'Shadow Monarch Dark Sovereign',
      category: 'Anime',
      badgeText: '⚔️ SHADOW LORD',
      referenceImagePath: 'assets/demo/ai_anime_art.jpg',
      likesCount: 13420,
      aspectRatio: '3:4',
      styleKeywords: ['Shadow Monarch', 'Purple Aura', 'Obsidian Armor', 'Manhwa Art'],
      prompt:
          'Epic dark fantasy manhwa anime portrait in the dramatic illustrative style of Solo Leveling. Imposing monarch figure clad in spiked obsidian armor with intricate glowing purple runic engravings, glowing neon violet flame aura surging violently from piercing glowing eyes and swirling around clenched fists. Swirling ethereal shadow soldier silhouettes rising from mist behind him with glowing blue eyes, lightning crackling across the dark stormy sky, extreme dynamic low-angle composition, hyper-detailed digital manhwa illustration, 8K wallpaper masterpiece.',
      negativePrompt: 'cheerful colors, wooden sword, simple flat shading, low quality, chibi',
      modelRecommendation: 'NijiJourney v6',
      lightingStyle: 'Neon Violet Spell Flames & Abyssal Lightning',
      cameraLens: 'Ultra-Wide 24mm Dynamic Perspective',
    ),
    const AiPhotoPresetEntity(
      id: 'photo_anime_flame_swordsman',
      title: 'Solar Flame Breathing Ronin',
      category: 'Anime',
      badgeText: '🔥 FLAME RONIN',
      referenceImagePath: 'assets/demo/ai_cyber_samurai.jpg',
      likesCount: 12180,
      aspectRatio: '3:4',
      styleKeywords: ['Flame Breathing', 'Solar Katana', 'Anime Swordsman', 'Harvest Moon'],
      prompt:
          'High-octane dynamic anime portrait of a fierce traditional swordsman executing a fiery sword dance beneath a blood-red harvest moon. Dual katanas enveloped in swirling arcs of realistic fluid fire, golden sparks and burning embers spiraling into the night sky, flowing patterned haori jacket billowing dramatically in the thermal updraft. Intense battle focus in fiery golden eyes, traditional ink splatter accents mingled with modern high-budget Ufotable digital effects, 8K ultra-vibrant anime artwork.',
      negativePrompt: 'blurry action, dull sword, western knight, modern clothing, cartoonish lowres',
      modelRecommendation: 'Midjourney v6.1 (Niji)',
      lightingStyle: 'Volumetric Fluid Fire Arc & Crimson Moon Radiance',
      cameraLens: '50mm Anamorphic Action Cine Lens',
    ),
    const AiPhotoPresetEntity(
      id: 'photo_anime_shinkai_summer',
      title: 'Shinkai Summer Rain Sky',
      category: 'Anime',
      badgeText: '🌧️ SUMMER SKY',
      referenceImagePath: 'assets/demo/ai_watercolor_dream.jpg',
      likesCount: 11050,
      aspectRatio: '3:4',
      styleKeywords: ['Makoto Shinkai', 'Double Rainbow', 'Volumetric Clouds', 'Rooftop Tokyo'],
      prompt:
          'Poetic and emotionally resonant anime portrait inspired by Makoto Shinkai’s Weathering with You and Your Name. Young protagonist standing atop an overgrown rooftop garden overlooking a panoramic Tokyo skyline just as storm clouds part, revealing a brilliant double rainbow. Spectacular volumetric cumulus clouds glowing with warm apricot and azure sunset light, crystalline raindrops falling in slow motion catching individual prismatic sun glints, hyper-detailed railway tracks and green train cars below, 8K CoMix Wave anime art.',
      negativePrompt: 'dark gloom, messy lines, flat boring sky, pixelated, 3D polygon look',
      modelRecommendation: 'Midjourney v6.1 (Niji)',
      lightingStyle: 'Sunset Breakthrough Golden Rays & Refracted Raindrops',
      cameraLens: '35mm Panavision Primo Anime Lens',
    ),
    const AiPhotoPresetEntity(
      id: 'photo_fantasy_phoenix_empress',
      title: 'Phoenix Flame Empress',
      category: 'Fantasy',
      badgeText: '👑 PHOENIX',
      referenceImagePath: 'assets/demo/ai_viking_warrior.jpg',
      likesCount: 10890,
      aspectRatio: '3:4',
      styleKeywords: ['Phoenix Wings', 'Molten Gold', 'Obsidian Throne', 'Mythical'],
      prompt:
          'Majestic high-fantasy portrait of a mythical Phoenix Empress standing upon an ancient volcanic obsidian throne. Spectacular wings composed of living golden flame and iridescent fiery plumes spreading wide behind her, embers drifting into the smoky twilight. Wearing an ornate scorched-gold filigree crown set with fiery carnelian gems, flowing crimson silk gown with embers burning at the hem, piercing radiant amber eyes with ancient wisdom. Dramatic contrast of dark volcanic stone and blinding golden firelight, Peter Mohrbacher angelic fantasy concept art, 8K masterwork.',
      negativePrompt: 'cold ice, frozen tundra, casual dress, blurry feathers, distorted face',
      modelRecommendation: 'Flux.1 Pro',
      lightingStyle: 'Radiant Living Flame Backlight & Smoldering Embers',
      cameraLens: '85mm f/1.2 Cine Prime',
    ),
    const AiPhotoPresetEntity(
      id: 'photo_fantasy_dragon_rider',
      title: 'Valyrian Dragon Sovereign',
      category: 'Fantasy',
      badgeText: '🐉 DRAGONLORD',
      referenceImagePath: 'assets/demo/ai_fantasy_elf.jpg',
      likesCount: 11750,
      aspectRatio: '3:4',
      styleKeywords: ['Dragon Rider', 'Platinum Hair', 'Valyrian Steel', 'Black Dragon'],
      prompt:
          'Cinematic dark fantasy portrait of a Valyrian dragonlord standing beside the colossal head of an ancient slumbering black dragon. Subject has long braided platinum-white hair, lilac-purple eyes, and high aristocratic cheekbones, dressed in boiled black leather and dragonscale armor with polished valyrian steel buckles. Giant dragon scales with iridescent sheen, wisps of warm smoke curling from the beast\'s giant nostrils, windswept misty volcanic mountain peak in the background, Game of Thrones cinematic photorealism, 8K resolution.',
      negativePrompt: 'modern buildings, cute cartoon dragon, plastic armor, bad anatomy, low quality',
      modelRecommendation: 'Midjourney v6.1',
      lightingStyle: 'Overcast Volcanic Peak & Warm Dragon Breath Embers',
      cameraLens: '70mm f/2.0 Anamorphic Telephoto',
    ),
    const AiPhotoPresetEntity(
      id: 'photo_fantasy_abyssal_kraken',
      title: 'Abyssal Deep-Sea Priestess',
      category: 'Fantasy',
      badgeText: '🐙 ABYSSAL',
      referenceImagePath: 'assets/demo/ai_underwater_siren.jpg',
      likesCount: 9640,
      aspectRatio: '3:4',
      styleKeywords: ['Deep Sea', 'Bioluminescent', 'Jellyfish', 'Oceanic Trench'],
      prompt:
          'Dark surreal fantasy portrait of an abyssal siren priestess ruling the midnight oceanic trenches. Bioluminescent deep-blue and emerald algae patterns glowing across pale porcelain skin, delicate translucent fin-like gills along the neck, elaborate headdress made of glowing sea anemones, polished black pearls, and spiral nautilus shells. Surrounded by floating luminescent jellyfish casting soft eerie volumetric glows through the deep dark ocean depths, mystical and otherworldly, 8K underwater fantasy concept art.',
      negativePrompt: 'sunny beach, swimming pool, cartoon fish, muddy water, distorted limbs',
      modelRecommendation: 'Flux.1 Pro',
      lightingStyle: 'Bioluminescent Cyan Caustics & Jellyfish Pulsing Light',
      cameraLens: '28mm Underwater Dome Cine Port',
    ),
    const AiPhotoPresetEntity(
      id: 'photo_vintage_super8_roadtrip',
      title: '1975 California Highway Super 8',
      category: 'Vintage',
      badgeText: '📼 SUPER 8',
      referenceImagePath: 'assets/demo/tmpl-retro-90s.jpg',
      likesCount: 8760,
      aspectRatio: '3:4',
      styleKeywords: ['Super 8mm', '1970s Roadtrip', 'Pacific Coast', 'Kodachrome'],
      prompt:
          'Warm nostalgic 1970s analog film snapshot captured on vintage Kodachrome Super 8mm motion film stock. Sun-tanned subject with feathered wind-blown hair leaning out the passenger window of a dusty 1972 Ford Bronco cruising along California Pacific Coast Highway 1. Radiant low-angle afternoon sun casting heavy amber lens flares and warm golden chromatic halation, sparkling ocean waves below cliffs, authentic vintage grain, dust scratches, and color bleed, timeless nostalgic Americana, 8K analog aesthetic.',
      negativePrompt: 'modern cars, smartphones, digital crispness, clean CGI, flat colors',
      modelRecommendation: 'Midjourney v6.1',
      lightingStyle: 'Golden Coastal Sun Flare & Warm Kodachrome Haze',
      cameraLens: 'Canon 514XL Super 8mm Zoom Lens',
    ),
    const AiPhotoPresetEntity(
      id: 'photo_vintage_90s_grunge',
      title: '1993 MTV Unplugged Grunge',
      category: 'Vintage',
      badgeText: '🎸 90s GRUNGE',
      referenceImagePath: 'assets/demo/ai_film_noir.jpg',
      likesCount: 8320,
      aspectRatio: '3:4',
      styleKeywords: ['90s Grunge', 'MTV Unplugged', 'Flannel Shirt', 'Seattle Sound'],
      prompt:
          'Moody authentic 1990s grunge rock portrait in the raw style of Seattle indie music photography. Subject sitting on an acoustic guitar flight case in a dim backstage green room, wearing an oversized distressed vintage thrifted flannel shirt over a torn band tee, chipped black nail polish, and tousled unbrushed grunge hair. Warm amber glow from a single hanging incandescent Edison bulb, cigarette smoke swirling through the frame, authentic Fuji Superia 800 film grain, raw emotional intimacy, 8K candid portrait.',
      negativePrompt: 'clean corporate studio, modern pop star, plastic look, oversaturated colors',
      modelRecommendation: 'Flux.1 Dev',
      lightingStyle: 'Single Incandescent Bare Bulb & Atmospheric Smoke',
      cameraLens: 'Nikon 50mm f/1.8D Analog Prime',
    ),
    const AiPhotoPresetEntity(
      id: 'photo_vintage_1920s_flapper',
      title: '1920s Great Gatsby Art Deco Flapper',
      category: 'Vintage',
      badgeText: '🥂 JAZZ AGE',
      referenceImagePath: 'assets/demo/ai_dark_academia.jpg',
      likesCount: 9140,
      aspectRatio: '3:4',
      styleKeywords: ['1920s Flapper', 'Great Gatsby', 'Beaded Dress', 'Art Deco'],
      prompt:
          'Decadent 1920s Roaring Twenties Jazz Age portrait inside a lavish Art Deco speakeasy ballroom. Glamorous flapper wearing an intricately hand-beaded silver fringe dress, silk satin opera gloves, and an elaborate diamond bandeau headband with a peacock feather plume. Holding a delicate crystal champagne coupe, soft warm amber ballroom chandelier lighting reflecting off geometric mirror-mosaic walls, rich sepia and gold duotone grading, authentic 1920s vintage elegance, 8K photorealism.',
      negativePrompt: 'modern clothing, neon lights, plastic jewelry, modern makeup style',
      modelRecommendation: 'Midjourney v6.1',
      lightingStyle: 'Crystal Chandelier Amber Warmth & Antique Mirror Bounce',
      cameraLens: 'Vintage 1920s Cooke Speed Panchro 75mm',
    ),
    const AiPhotoPresetEntity(
      id: 'photo_3d_pixar_chef',
      title: 'Whimsical 3D Animated Master Chef',
      category: '3D Pixar',
      badgeText: '🥐 MASTER CHEF',
      referenceImagePath: 'assets/demo/ai_3d_render.jpg',
      likesCount: 9780,
      aspectRatio: '3:4',
      styleKeywords: ['Pixar Chef', 'Croissant', 'Paris Bakery', 'Warm Kitchen'],
      prompt:
          'Heartwarming 3D animated character portrait of an enthusiastic young French pastry chef in a cozy Parisian bakery kitchen. Big expressive hazel eyes sparkling with passion, a light dusting of white flour on cute rosy cheeks, towering tall white chef toque hat perched slightly askew. Holding a freshly baked golden-brown croissant with delicate flaky layers and rising warm steam, background filled with copper pots, wooden rolling pins, and warm brick oven fire glow, Disney Pixar Ratatouille aesthetic, 8K Octane render.',
      negativePrompt: 'ugly clay, flat textures, realistic scary human, dark gloomy room',
      modelRecommendation: 'Midjourney v6.1',
      lightingStyle: 'Cozy Brick Oven Fireplace & Warm Bakery Sunlight',
      cameraLens: 'Pixar Virtual 50mm Prime Camera',
    ),
    const AiPhotoPresetEntity(
      id: 'photo_3d_cute_robot',
      title: '3D Miniature Companion Robot',
      category: '3D Pixar',
      badgeText: '🤖 CUTE BOT',
      referenceImagePath: 'assets/demo/ai_3d_render.jpg',
      likesCount: 10640,
      aspectRatio: '3:4',
      styleKeywords: ['Cute Robot', 'LED Eyes', 'Sunflower', 'Cozy 3D'],
      prompt:
          'Adorable 3D animated companion robot character portrait sitting on a sunlit wooden windowsill beside a blooming potted sunflower. Round ceramic body with smooth white matte finish, oversized turquoise LED glowing digital eye screens displaying happy curved emoticon eyes, tiny brass antennae twitching with curious energy. Soft afternoon sunbeam illuminating dust motes, realistic micro-scratches on polished plastic, Wall-E and Big Hero 6 design harmony, 8K 3D animated render.',
      negativePrompt: 'scary killer terminator, rusty junk, dull colors, low polygon mesh',
      modelRecommendation: 'Flux.1 Pro',
      lightingStyle: 'Warm Golden Window Sunbeam & Soft Ambient Dust',
      cameraLens: 'Macro 60mm f/2.8 Depth of Field Lens',
    ),
    const AiPhotoPresetEntity(
      id: 'photo_cinematic_aurora_dancer',
      title: 'Northern Lights Aurora Borealis',
      category: 'Cinematic',
      badgeText: '🌌 AURORA',
      referenceImagePath: 'assets/demo/ai_cosmic_astronaut.jpg',
      likesCount: 12890,
      aspectRatio: '3:4',
      styleKeywords: ['Northern Lights', 'Tromso Norway', 'Arctic Parka', 'Starry Sky'],
      prompt:
          'Breathtaking arctic night cinematic portrait of a nomadic aurora dancer standing atop a snow-covered ridge in Tromsø, Norway. Swirling celestial ribbons of emerald green, violet, and electric magenta Northern Lights illuminating the vast night sky and reflecting on snow crystals. Wearing a traditional Sami-embroidered wool parka lined with thick arctic fox fur, cold breath condensing in the crisp sub-zero air, stars pin-sharp in the dark sky, National Geographic expedition cinematography, 8K resolution.',
      negativePrompt: 'cloudy gray sky, city buildings, daytime, plastic fur, blurry stars',
      modelRecommendation: 'Flux.1 Pro',
      lightingStyle: 'Natural Aurora Borealis Emerald & Magenta Glow',
      cameraLens: '24mm f/1.4 Ultra-Wide Astrophotography Lens',
    ),
    const AiPhotoPresetEntity(
      id: 'photo_cinematic_sandstorm_nomad',
      title: 'Sahara Sandstorm Desert Wanderer',
      category: 'Cinematic',
      badgeText: '🏜️ NOMAD',
      referenceImagePath: 'assets/demo/tmpl-golden-hour.jpg',
      likesCount: 11420,
      aspectRatio: '3:4',
      styleKeywords: ['Sandstorm Nomad', 'Sahara Dunes', 'Tagelmust Veil', 'Dune Aesthetic'],
      prompt:
          'Epic high-tension cinematic portrait of a solitary Berber nomad navigating through a blinding Sahara sandstorm at twilight. Wearing indigo-dyed tagelmust turban and veil wrapped tightly across the face, exposing only fierce weathered hazel eyes lined with natural kohl. Dramatic golden and ochre sand particles frozen mid-air like rushing curtains of gold dust, towering shifting dunes disappearing into the orange haze, Dune and Lawrence of Arabia cinematographic atmosphere, 8K masterwork.',
      negativePrompt: 'calm clear beach, modern sunglasses, flat lighting, clean indoor setting',
      modelRecommendation: 'Midjourney v6.1',
      lightingStyle: 'Amber Twilight Dusk & Backlit Sand Granules',
      cameraLens: '85mm f/1.4 Anamorphic Cine Prime',
    ),
    const AiPhotoPresetEntity(
      id: 'photo_trending_kpop_ice_prince',
      title: 'K-Pop Winter Diamond Frost',
      category: 'Trending',
      badgeText: '❄️ ICE IDOL',
      referenceImagePath: 'assets/demo/ai_fashion_editorial.jpg',
      likesCount: 12900,
      aspectRatio: '3:4',
      styleKeywords: ['K-Pop Frost', 'Silver Hair', 'Ice Crystals', 'White Velvet'],
      prompt:
          'Mesmerizing winter concept K-Pop idol portrait set inside a crystalline ice palace stage. Striking silver-white styled hair with delicate frost crystals dusted onto eyelashes and cheekbones, mesmerizing pale ice-blue contact lenses, tailored structured white velvet military blazer adorned with dangling silver chains and icy Swarovski frost brooches. Ethereal cold blue and soft violet volumetric stage backlights casting a luminous halo, fine falling snow particles frozen in mid-air, Vogue Korea high-fashion editorial quality, 8K resolution.',
      negativePrompt: 'sweaty warm summer, casual clothes, dark muddy colors, bad facial symmetry',
      modelRecommendation: 'Flux.1 Pro',
      lightingStyle: 'Cold Cyan Rim Light & Ethereal Frost Halo',
      cameraLens: '105mm f/1.4 Bokeh Master Telephoto',
    ),
"""

dart_path = '/Users/apple/Desktop/ProCut/lib/features/ai_photo_edit/data/ai_photo_presets_data.dart'
with open(dart_path, 'r', encoding='utf-8') as f:
    text = f.read()

# Insert before the last '  ];\n}'
target = '  ];\n}'
if target in text:
    text = text.replace(target, NEW_PRESETS_DART + target)
    with open(dart_path, 'w', encoding='utf-8') as f:
        f.write(text)
    print("Successfully added 20 new presets to Dart file!")
else:
    print("Error: Could not find target insertion point in Dart file.")
